// Code generated by "stringer -type=SystemMessageType"; DO NOT EDIT.

package multi

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SystemMessageDefault-0]
	_ = x[SystemMessageSending-1]
	_ = x[SystemMessageDelivered-2]
	_ = x[SystemMessageProcessed-3]
}

const _SystemMessageType_name = "SystemMessageDefaultSystemMessageSendingSystemMessageDeliveredSystemMessageProcessed"

var _SystemMessageType_index = [...]uint8{0, 20, 40, 62, 84}

func (i SystemMessageType) String() string {
	if i < 0 || i >= SystemMessageType(len(_SystemMessageType_index)-1) {
		return "SystemMessageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SystemMessageType_name[_SystemMessageType_index[i]:_SystemMessageType_index[i+1]]
}
