/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package convex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestAgentsListByStatusArgs type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestAgentsListByStatusArgs{}

// RequestAgentsListByStatusArgs struct for RequestAgentsListByStatusArgs
type RequestAgentsListByStatusArgs struct {
	Status RequestAgentsListByStatusArgsStatus `json:"status"`
}

type _RequestAgentsListByStatusArgs RequestAgentsListByStatusArgs

// NewRequestAgentsListByStatusArgs instantiates a new RequestAgentsListByStatusArgs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestAgentsListByStatusArgs(status RequestAgentsListByStatusArgsStatus) *RequestAgentsListByStatusArgs {
	this := RequestAgentsListByStatusArgs{}
	this.Status = status
	return &this
}

// NewRequestAgentsListByStatusArgsWithDefaults instantiates a new RequestAgentsListByStatusArgs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestAgentsListByStatusArgsWithDefaults() *RequestAgentsListByStatusArgs {
	this := RequestAgentsListByStatusArgs{}
	return &this
}

// GetStatus returns the Status field value
func (o *RequestAgentsListByStatusArgs) GetStatus() RequestAgentsListByStatusArgsStatus {
	if o == nil {
		var ret RequestAgentsListByStatusArgsStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *RequestAgentsListByStatusArgs) GetStatusOk() (*RequestAgentsListByStatusArgsStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *RequestAgentsListByStatusArgs) SetStatus(v RequestAgentsListByStatusArgsStatus) {
	o.Status = v
}

func (o RequestAgentsListByStatusArgs) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestAgentsListByStatusArgs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *RequestAgentsListByStatusArgs) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestAgentsListByStatusArgs := _RequestAgentsListByStatusArgs{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestAgentsListByStatusArgs)

	if err != nil {
		return err
	}

	*o = RequestAgentsListByStatusArgs(varRequestAgentsListByStatusArgs)

	return err
}

type NullableRequestAgentsListByStatusArgs struct {
	value *RequestAgentsListByStatusArgs
	isSet bool
}

func (v NullableRequestAgentsListByStatusArgs) Get() *RequestAgentsListByStatusArgs {
	return v.value
}

func (v *NullableRequestAgentsListByStatusArgs) Set(val *RequestAgentsListByStatusArgs) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestAgentsListByStatusArgs) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestAgentsListByStatusArgs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestAgentsListByStatusArgs(val *RequestAgentsListByStatusArgs) *NullableRequestAgentsListByStatusArgs {
	return &NullableRequestAgentsListByStatusArgs{value: val, isSet: true}
}

func (v NullableRequestAgentsListByStatusArgs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestAgentsListByStatusArgs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


