/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package convex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestEventsSubscribeToProjectArgs type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestEventsSubscribeToProjectArgs{}

// RequestEventsSubscribeToProjectArgs struct for RequestEventsSubscribeToProjectArgs
type RequestEventsSubscribeToProjectArgs struct {
	ProjectId string `json:"projectId"`
	Since *float32 `json:"since,omitempty"`
}

type _RequestEventsSubscribeToProjectArgs RequestEventsSubscribeToProjectArgs

// NewRequestEventsSubscribeToProjectArgs instantiates a new RequestEventsSubscribeToProjectArgs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestEventsSubscribeToProjectArgs(projectId string) *RequestEventsSubscribeToProjectArgs {
	this := RequestEventsSubscribeToProjectArgs{}
	this.ProjectId = projectId
	return &this
}

// NewRequestEventsSubscribeToProjectArgsWithDefaults instantiates a new RequestEventsSubscribeToProjectArgs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestEventsSubscribeToProjectArgsWithDefaults() *RequestEventsSubscribeToProjectArgs {
	this := RequestEventsSubscribeToProjectArgs{}
	return &this
}

// GetProjectId returns the ProjectId field value
func (o *RequestEventsSubscribeToProjectArgs) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *RequestEventsSubscribeToProjectArgs) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *RequestEventsSubscribeToProjectArgs) SetProjectId(v string) {
	o.ProjectId = v
}

// GetSince returns the Since field value if set, zero value otherwise.
func (o *RequestEventsSubscribeToProjectArgs) GetSince() float32 {
	if o == nil || IsNil(o.Since) {
		var ret float32
		return ret
	}
	return *o.Since
}

// GetSinceOk returns a tuple with the Since field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestEventsSubscribeToProjectArgs) GetSinceOk() (*float32, bool) {
	if o == nil || IsNil(o.Since) {
		return nil, false
	}
	return o.Since, true
}

// HasSince returns a boolean if a field has been set.
func (o *RequestEventsSubscribeToProjectArgs) HasSince() bool {
	if o != nil && !IsNil(o.Since) {
		return true
	}

	return false
}

// SetSince gets a reference to the given float32 and assigns it to the Since field.
func (o *RequestEventsSubscribeToProjectArgs) SetSince(v float32) {
	o.Since = &v
}

func (o RequestEventsSubscribeToProjectArgs) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestEventsSubscribeToProjectArgs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["projectId"] = o.ProjectId
	if !IsNil(o.Since) {
		toSerialize["since"] = o.Since
	}
	return toSerialize, nil
}

func (o *RequestEventsSubscribeToProjectArgs) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"projectId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestEventsSubscribeToProjectArgs := _RequestEventsSubscribeToProjectArgs{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestEventsSubscribeToProjectArgs)

	if err != nil {
		return err
	}

	*o = RequestEventsSubscribeToProjectArgs(varRequestEventsSubscribeToProjectArgs)

	return err
}

type NullableRequestEventsSubscribeToProjectArgs struct {
	value *RequestEventsSubscribeToProjectArgs
	isSet bool
}

func (v NullableRequestEventsSubscribeToProjectArgs) Get() *RequestEventsSubscribeToProjectArgs {
	return v.value
}

func (v *NullableRequestEventsSubscribeToProjectArgs) Set(val *RequestEventsSubscribeToProjectArgs) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestEventsSubscribeToProjectArgs) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestEventsSubscribeToProjectArgs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestEventsSubscribeToProjectArgs(val *RequestEventsSubscribeToProjectArgs) *NullableRequestEventsSubscribeToProjectArgs {
	return &NullableRequestEventsSubscribeToProjectArgs{value: val, isSet: true}
}

func (v NullableRequestEventsSubscribeToProjectArgs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestEventsSubscribeToProjectArgs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


