/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package convex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestAgentsUpdateStatusArgs type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestAgentsUpdateStatusArgs{}

// RequestAgentsUpdateStatusArgs struct for RequestAgentsUpdateStatusArgs
type RequestAgentsUpdateStatusArgs struct {
	Id string `json:"id"`
	IsStreaming *bool `json:"isStreaming,omitempty"`
	Status RequestAgentsListByStatusArgsStatus `json:"status"`
}

type _RequestAgentsUpdateStatusArgs RequestAgentsUpdateStatusArgs

// NewRequestAgentsUpdateStatusArgs instantiates a new RequestAgentsUpdateStatusArgs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestAgentsUpdateStatusArgs(id string, status RequestAgentsListByStatusArgsStatus) *RequestAgentsUpdateStatusArgs {
	this := RequestAgentsUpdateStatusArgs{}
	this.Id = id
	this.Status = status
	return &this
}

// NewRequestAgentsUpdateStatusArgsWithDefaults instantiates a new RequestAgentsUpdateStatusArgs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestAgentsUpdateStatusArgsWithDefaults() *RequestAgentsUpdateStatusArgs {
	this := RequestAgentsUpdateStatusArgs{}
	return &this
}

// GetId returns the Id field value
func (o *RequestAgentsUpdateStatusArgs) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RequestAgentsUpdateStatusArgs) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RequestAgentsUpdateStatusArgs) SetId(v string) {
	o.Id = v
}

// GetIsStreaming returns the IsStreaming field value if set, zero value otherwise.
func (o *RequestAgentsUpdateStatusArgs) GetIsStreaming() bool {
	if o == nil || IsNil(o.IsStreaming) {
		var ret bool
		return ret
	}
	return *o.IsStreaming
}

// GetIsStreamingOk returns a tuple with the IsStreaming field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestAgentsUpdateStatusArgs) GetIsStreamingOk() (*bool, bool) {
	if o == nil || IsNil(o.IsStreaming) {
		return nil, false
	}
	return o.IsStreaming, true
}

// HasIsStreaming returns a boolean if a field has been set.
func (o *RequestAgentsUpdateStatusArgs) HasIsStreaming() bool {
	if o != nil && !IsNil(o.IsStreaming) {
		return true
	}

	return false
}

// SetIsStreaming gets a reference to the given bool and assigns it to the IsStreaming field.
func (o *RequestAgentsUpdateStatusArgs) SetIsStreaming(v bool) {
	o.IsStreaming = &v
}

// GetStatus returns the Status field value
func (o *RequestAgentsUpdateStatusArgs) GetStatus() RequestAgentsListByStatusArgsStatus {
	if o == nil {
		var ret RequestAgentsListByStatusArgsStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *RequestAgentsUpdateStatusArgs) GetStatusOk() (*RequestAgentsListByStatusArgsStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *RequestAgentsUpdateStatusArgs) SetStatus(v RequestAgentsListByStatusArgsStatus) {
	o.Status = v
}

func (o RequestAgentsUpdateStatusArgs) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestAgentsUpdateStatusArgs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.IsStreaming) {
		toSerialize["isStreaming"] = o.IsStreaming
	}
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *RequestAgentsUpdateStatusArgs) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestAgentsUpdateStatusArgs := _RequestAgentsUpdateStatusArgs{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestAgentsUpdateStatusArgs)

	if err != nil {
		return err
	}

	*o = RequestAgentsUpdateStatusArgs(varRequestAgentsUpdateStatusArgs)

	return err
}

type NullableRequestAgentsUpdateStatusArgs struct {
	value *RequestAgentsUpdateStatusArgs
	isSet bool
}

func (v NullableRequestAgentsUpdateStatusArgs) Get() *RequestAgentsUpdateStatusArgs {
	return v.value
}

func (v *NullableRequestAgentsUpdateStatusArgs) Set(val *RequestAgentsUpdateStatusArgs) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestAgentsUpdateStatusArgs) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestAgentsUpdateStatusArgs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestAgentsUpdateStatusArgs(val *RequestAgentsUpdateStatusArgs) *NullableRequestAgentsUpdateStatusArgs {
	return &NullableRequestAgentsUpdateStatusArgs{value: val, isSet: true}
}

func (v NullableRequestAgentsUpdateStatusArgs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestAgentsUpdateStatusArgs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


