/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package convex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ResponseAgentsGetWithTasks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseAgentsGetWithTasks{}

// ResponseAgentsGetWithTasks struct for ResponseAgentsGetWithTasks
type ResponseAgentsGetWithTasks struct {
	Status string `json:"status"`
	ErrorMessage *string `json:"errorMessage,omitempty"`
	ErrorData map[string]interface{} `json:"errorData,omitempty"`
	Value interface{} `json:"value,omitempty"`
}

type _ResponseAgentsGetWithTasks ResponseAgentsGetWithTasks

// NewResponseAgentsGetWithTasks instantiates a new ResponseAgentsGetWithTasks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseAgentsGetWithTasks(status string) *ResponseAgentsGetWithTasks {
	this := ResponseAgentsGetWithTasks{}
	this.Status = status
	return &this
}

// NewResponseAgentsGetWithTasksWithDefaults instantiates a new ResponseAgentsGetWithTasks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseAgentsGetWithTasksWithDefaults() *ResponseAgentsGetWithTasks {
	this := ResponseAgentsGetWithTasks{}
	return &this
}

// GetStatus returns the Status field value
func (o *ResponseAgentsGetWithTasks) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ResponseAgentsGetWithTasks) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ResponseAgentsGetWithTasks) SetStatus(v string) {
	o.Status = v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise.
func (o *ResponseAgentsGetWithTasks) GetErrorMessage() string {
	if o == nil || IsNil(o.ErrorMessage) {
		var ret string
		return ret
	}
	return *o.ErrorMessage
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseAgentsGetWithTasks) GetErrorMessageOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorMessage) {
		return nil, false
	}
	return o.ErrorMessage, true
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *ResponseAgentsGetWithTasks) HasErrorMessage() bool {
	if o != nil && !IsNil(o.ErrorMessage) {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given string and assigns it to the ErrorMessage field.
func (o *ResponseAgentsGetWithTasks) SetErrorMessage(v string) {
	o.ErrorMessage = &v
}

// GetErrorData returns the ErrorData field value if set, zero value otherwise.
func (o *ResponseAgentsGetWithTasks) GetErrorData() map[string]interface{} {
	if o == nil || IsNil(o.ErrorData) {
		var ret map[string]interface{}
		return ret
	}
	return o.ErrorData
}

// GetErrorDataOk returns a tuple with the ErrorData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseAgentsGetWithTasks) GetErrorDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ErrorData) {
		return map[string]interface{}{}, false
	}
	return o.ErrorData, true
}

// HasErrorData returns a boolean if a field has been set.
func (o *ResponseAgentsGetWithTasks) HasErrorData() bool {
	if o != nil && !IsNil(o.ErrorData) {
		return true
	}

	return false
}

// SetErrorData gets a reference to the given map[string]interface{} and assigns it to the ErrorData field.
func (o *ResponseAgentsGetWithTasks) SetErrorData(v map[string]interface{}) {
	o.ErrorData = v
}

// GetValue returns the Value field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ResponseAgentsGetWithTasks) GetValue() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ResponseAgentsGetWithTasks) GetValueOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return &o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ResponseAgentsGetWithTasks) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given interface{} and assigns it to the Value field.
func (o *ResponseAgentsGetWithTasks) SetValue(v interface{}) {
	o.Value = v
}

func (o ResponseAgentsGetWithTasks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseAgentsGetWithTasks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	if !IsNil(o.ErrorMessage) {
		toSerialize["errorMessage"] = o.ErrorMessage
	}
	if !IsNil(o.ErrorData) {
		toSerialize["errorData"] = o.ErrorData
	}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

func (o *ResponseAgentsGetWithTasks) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResponseAgentsGetWithTasks := _ResponseAgentsGetWithTasks{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResponseAgentsGetWithTasks)

	if err != nil {
		return err
	}

	*o = ResponseAgentsGetWithTasks(varResponseAgentsGetWithTasks)

	return err
}

type NullableResponseAgentsGetWithTasks struct {
	value *ResponseAgentsGetWithTasks
	isSet bool
}

func (v NullableResponseAgentsGetWithTasks) Get() *ResponseAgentsGetWithTasks {
	return v.value
}

func (v *NullableResponseAgentsGetWithTasks) Set(val *ResponseAgentsGetWithTasks) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseAgentsGetWithTasks) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseAgentsGetWithTasks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseAgentsGetWithTasks(val *ResponseAgentsGetWithTasks) *NullableResponseAgentsGetWithTasks {
	return &NullableResponseAgentsGetWithTasks{value: val, isSet: true}
}

func (v NullableResponseAgentsGetWithTasks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseAgentsGetWithTasks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


