/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package convex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestEventsSubscribeToProject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestEventsSubscribeToProject{}

// RequestEventsSubscribeToProject struct for RequestEventsSubscribeToProject
type RequestEventsSubscribeToProject struct {
	Args RequestEventsSubscribeToProjectArgs `json:"args"`
}

type _RequestEventsSubscribeToProject RequestEventsSubscribeToProject

// NewRequestEventsSubscribeToProject instantiates a new RequestEventsSubscribeToProject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestEventsSubscribeToProject(args RequestEventsSubscribeToProjectArgs) *RequestEventsSubscribeToProject {
	this := RequestEventsSubscribeToProject{}
	this.Args = args
	return &this
}

// NewRequestEventsSubscribeToProjectWithDefaults instantiates a new RequestEventsSubscribeToProject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestEventsSubscribeToProjectWithDefaults() *RequestEventsSubscribeToProject {
	this := RequestEventsSubscribeToProject{}
	return &this
}

// GetArgs returns the Args field value
func (o *RequestEventsSubscribeToProject) GetArgs() RequestEventsSubscribeToProjectArgs {
	if o == nil {
		var ret RequestEventsSubscribeToProjectArgs
		return ret
	}

	return o.Args
}

// GetArgsOk returns a tuple with the Args field value
// and a boolean to check if the value has been set.
func (o *RequestEventsSubscribeToProject) GetArgsOk() (*RequestEventsSubscribeToProjectArgs, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Args, true
}

// SetArgs sets field value
func (o *RequestEventsSubscribeToProject) SetArgs(v RequestEventsSubscribeToProjectArgs) {
	o.Args = v
}

func (o RequestEventsSubscribeToProject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestEventsSubscribeToProject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["args"] = o.Args
	return toSerialize, nil
}

func (o *RequestEventsSubscribeToProject) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"args",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestEventsSubscribeToProject := _RequestEventsSubscribeToProject{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestEventsSubscribeToProject)

	if err != nil {
		return err
	}

	*o = RequestEventsSubscribeToProject(varRequestEventsSubscribeToProject)

	return err
}

type NullableRequestEventsSubscribeToProject struct {
	value *RequestEventsSubscribeToProject
	isSet bool
}

func (v NullableRequestEventsSubscribeToProject) Get() *RequestEventsSubscribeToProject {
	return v.value
}

func (v *NullableRequestEventsSubscribeToProject) Set(val *RequestEventsSubscribeToProject) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestEventsSubscribeToProject) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestEventsSubscribeToProject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestEventsSubscribeToProject(val *RequestEventsSubscribeToProject) *NullableRequestEventsSubscribeToProject {
	return &NullableRequestEventsSubscribeToProject{value: val, isSet: true}
}

func (v NullableRequestEventsSubscribeToProject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestEventsSubscribeToProject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


