/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package convex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestAgentsListByRoleArgs type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestAgentsListByRoleArgs{}

// RequestAgentsListByRoleArgs struct for RequestAgentsListByRoleArgs
type RequestAgentsListByRoleArgs struct {
	Role RequestAgentsListByRoleArgsRole `json:"role"`
}

type _RequestAgentsListByRoleArgs RequestAgentsListByRoleArgs

// NewRequestAgentsListByRoleArgs instantiates a new RequestAgentsListByRoleArgs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestAgentsListByRoleArgs(role RequestAgentsListByRoleArgsRole) *RequestAgentsListByRoleArgs {
	this := RequestAgentsListByRoleArgs{}
	this.Role = role
	return &this
}

// NewRequestAgentsListByRoleArgsWithDefaults instantiates a new RequestAgentsListByRoleArgs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestAgentsListByRoleArgsWithDefaults() *RequestAgentsListByRoleArgs {
	this := RequestAgentsListByRoleArgs{}
	return &this
}

// GetRole returns the Role field value
func (o *RequestAgentsListByRoleArgs) GetRole() RequestAgentsListByRoleArgsRole {
	if o == nil {
		var ret RequestAgentsListByRoleArgsRole
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *RequestAgentsListByRoleArgs) GetRoleOk() (*RequestAgentsListByRoleArgsRole, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *RequestAgentsListByRoleArgs) SetRole(v RequestAgentsListByRoleArgsRole) {
	o.Role = v
}

func (o RequestAgentsListByRoleArgs) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestAgentsListByRoleArgs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["role"] = o.Role
	return toSerialize, nil
}

func (o *RequestAgentsListByRoleArgs) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"role",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestAgentsListByRoleArgs := _RequestAgentsListByRoleArgs{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestAgentsListByRoleArgs)

	if err != nil {
		return err
	}

	*o = RequestAgentsListByRoleArgs(varRequestAgentsListByRoleArgs)

	return err
}

type NullableRequestAgentsListByRoleArgs struct {
	value *RequestAgentsListByRoleArgs
	isSet bool
}

func (v NullableRequestAgentsListByRoleArgs) Get() *RequestAgentsListByRoleArgs {
	return v.value
}

func (v *NullableRequestAgentsListByRoleArgs) Set(val *RequestAgentsListByRoleArgs) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestAgentsListByRoleArgs) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestAgentsListByRoleArgs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestAgentsListByRoleArgs(val *RequestAgentsListByRoleArgs) *NullableRequestAgentsListByRoleArgs {
	return &NullableRequestAgentsListByRoleArgs{value: val, isSet: true}
}

func (v NullableRequestAgentsListByRoleArgs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestAgentsListByRoleArgs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


