/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package convex

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// RequestAgentsListByStatusArgsStatus - struct for RequestAgentsListByStatusArgsStatus
type RequestAgentsListByStatusArgsStatus struct {
	String *string
}

// stringAsRequestAgentsListByStatusArgsStatus is a convenience function that returns string wrapped in RequestAgentsListByStatusArgsStatus
func StringAsRequestAgentsListByStatusArgsStatus(v *string) RequestAgentsListByStatusArgsStatus {
	return RequestAgentsListByStatusArgsStatus{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *RequestAgentsListByStatusArgsStatus) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(RequestAgentsListByStatusArgsStatus)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(RequestAgentsListByStatusArgsStatus)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src RequestAgentsListByStatusArgsStatus) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *RequestAgentsListByStatusArgsStatus) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj RequestAgentsListByStatusArgsStatus) GetActualInstanceValue() (interface{}) {
	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableRequestAgentsListByStatusArgsStatus struct {
	value *RequestAgentsListByStatusArgsStatus
	isSet bool
}

func (v NullableRequestAgentsListByStatusArgsStatus) Get() *RequestAgentsListByStatusArgsStatus {
	return v.value
}

func (v *NullableRequestAgentsListByStatusArgsStatus) Set(val *RequestAgentsListByStatusArgsStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestAgentsListByStatusArgsStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestAgentsListByStatusArgsStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestAgentsListByStatusArgsStatus(val *RequestAgentsListByStatusArgsStatus) *NullableRequestAgentsListByStatusArgsStatus {
	return &NullableRequestAgentsListByStatusArgsStatus{value: val, isSet: true}
}

func (v NullableRequestAgentsListByStatusArgsStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestAgentsListByStatusArgsStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


