/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package convex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestSettingsUpdateTheme type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestSettingsUpdateTheme{}

// RequestSettingsUpdateTheme struct for RequestSettingsUpdateTheme
type RequestSettingsUpdateTheme struct {
	Args RequestSettingsUpdateThemeArgs `json:"args"`
}

type _RequestSettingsUpdateTheme RequestSettingsUpdateTheme

// NewRequestSettingsUpdateTheme instantiates a new RequestSettingsUpdateTheme object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestSettingsUpdateTheme(args RequestSettingsUpdateThemeArgs) *RequestSettingsUpdateTheme {
	this := RequestSettingsUpdateTheme{}
	this.Args = args
	return &this
}

// NewRequestSettingsUpdateThemeWithDefaults instantiates a new RequestSettingsUpdateTheme object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestSettingsUpdateThemeWithDefaults() *RequestSettingsUpdateTheme {
	this := RequestSettingsUpdateTheme{}
	return &this
}

// GetArgs returns the Args field value
func (o *RequestSettingsUpdateTheme) GetArgs() RequestSettingsUpdateThemeArgs {
	if o == nil {
		var ret RequestSettingsUpdateThemeArgs
		return ret
	}

	return o.Args
}

// GetArgsOk returns a tuple with the Args field value
// and a boolean to check if the value has been set.
func (o *RequestSettingsUpdateTheme) GetArgsOk() (*RequestSettingsUpdateThemeArgs, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Args, true
}

// SetArgs sets field value
func (o *RequestSettingsUpdateTheme) SetArgs(v RequestSettingsUpdateThemeArgs) {
	o.Args = v
}

func (o RequestSettingsUpdateTheme) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestSettingsUpdateTheme) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["args"] = o.Args
	return toSerialize, nil
}

func (o *RequestSettingsUpdateTheme) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"args",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestSettingsUpdateTheme := _RequestSettingsUpdateTheme{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestSettingsUpdateTheme)

	if err != nil {
		return err
	}

	*o = RequestSettingsUpdateTheme(varRequestSettingsUpdateTheme)

	return err
}

type NullableRequestSettingsUpdateTheme struct {
	value *RequestSettingsUpdateTheme
	isSet bool
}

func (v NullableRequestSettingsUpdateTheme) Get() *RequestSettingsUpdateTheme {
	return v.value
}

func (v *NullableRequestSettingsUpdateTheme) Set(val *RequestSettingsUpdateTheme) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestSettingsUpdateTheme) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestSettingsUpdateTheme) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestSettingsUpdateTheme(val *RequestSettingsUpdateTheme) *NullableRequestSettingsUpdateTheme {
	return &NullableRequestSettingsUpdateTheme{value: val, isSet: true}
}

func (v NullableRequestSettingsUpdateTheme) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestSettingsUpdateTheme) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


