/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package convex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestProjectsGetWithStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestProjectsGetWithStats{}

// RequestProjectsGetWithStats struct for RequestProjectsGetWithStats
type RequestProjectsGetWithStats struct {
	Args RequestAgentsGetArgs `json:"args"`
}

type _RequestProjectsGetWithStats RequestProjectsGetWithStats

// NewRequestProjectsGetWithStats instantiates a new RequestProjectsGetWithStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestProjectsGetWithStats(args RequestAgentsGetArgs) *RequestProjectsGetWithStats {
	this := RequestProjectsGetWithStats{}
	this.Args = args
	return &this
}

// NewRequestProjectsGetWithStatsWithDefaults instantiates a new RequestProjectsGetWithStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestProjectsGetWithStatsWithDefaults() *RequestProjectsGetWithStats {
	this := RequestProjectsGetWithStats{}
	return &this
}

// GetArgs returns the Args field value
func (o *RequestProjectsGetWithStats) GetArgs() RequestAgentsGetArgs {
	if o == nil {
		var ret RequestAgentsGetArgs
		return ret
	}

	return o.Args
}

// GetArgsOk returns a tuple with the Args field value
// and a boolean to check if the value has been set.
func (o *RequestProjectsGetWithStats) GetArgsOk() (*RequestAgentsGetArgs, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Args, true
}

// SetArgs sets field value
func (o *RequestProjectsGetWithStats) SetArgs(v RequestAgentsGetArgs) {
	o.Args = v
}

func (o RequestProjectsGetWithStats) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestProjectsGetWithStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["args"] = o.Args
	return toSerialize, nil
}

func (o *RequestProjectsGetWithStats) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"args",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestProjectsGetWithStats := _RequestProjectsGetWithStats{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestProjectsGetWithStats)

	if err != nil {
		return err
	}

	*o = RequestProjectsGetWithStats(varRequestProjectsGetWithStats)

	return err
}

type NullableRequestProjectsGetWithStats struct {
	value *RequestProjectsGetWithStats
	isSet bool
}

func (v NullableRequestProjectsGetWithStats) Get() *RequestProjectsGetWithStats {
	return v.value
}

func (v *NullableRequestProjectsGetWithStats) Set(val *RequestProjectsGetWithStats) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestProjectsGetWithStats) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestProjectsGetWithStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestProjectsGetWithStats(val *RequestProjectsGetWithStats) *NullableRequestProjectsGetWithStats {
	return &NullableRequestProjectsGetWithStats{value: val, isSet: true}
}

func (v NullableRequestProjectsGetWithStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestProjectsGetWithStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


