/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package convex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestProjectsCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestProjectsCreate{}

// RequestProjectsCreate struct for RequestProjectsCreate
type RequestProjectsCreate struct {
	Args RequestProjectsCreateArgs `json:"args"`
}

type _RequestProjectsCreate RequestProjectsCreate

// NewRequestProjectsCreate instantiates a new RequestProjectsCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestProjectsCreate(args RequestProjectsCreateArgs) *RequestProjectsCreate {
	this := RequestProjectsCreate{}
	this.Args = args
	return &this
}

// NewRequestProjectsCreateWithDefaults instantiates a new RequestProjectsCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestProjectsCreateWithDefaults() *RequestProjectsCreate {
	this := RequestProjectsCreate{}
	return &this
}

// GetArgs returns the Args field value
func (o *RequestProjectsCreate) GetArgs() RequestProjectsCreateArgs {
	if o == nil {
		var ret RequestProjectsCreateArgs
		return ret
	}

	return o.Args
}

// GetArgsOk returns a tuple with the Args field value
// and a boolean to check if the value has been set.
func (o *RequestProjectsCreate) GetArgsOk() (*RequestProjectsCreateArgs, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Args, true
}

// SetArgs sets field value
func (o *RequestProjectsCreate) SetArgs(v RequestProjectsCreateArgs) {
	o.Args = v
}

func (o RequestProjectsCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestProjectsCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["args"] = o.Args
	return toSerialize, nil
}

func (o *RequestProjectsCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"args",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestProjectsCreate := _RequestProjectsCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestProjectsCreate)

	if err != nil {
		return err
	}

	*o = RequestProjectsCreate(varRequestProjectsCreate)

	return err
}

type NullableRequestProjectsCreate struct {
	value *RequestProjectsCreate
	isSet bool
}

func (v NullableRequestProjectsCreate) Get() *RequestProjectsCreate {
	return v.value
}

func (v *NullableRequestProjectsCreate) Set(val *RequestProjectsCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestProjectsCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestProjectsCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestProjectsCreate(val *RequestProjectsCreate) *NullableRequestProjectsCreate {
	return &NullableRequestProjectsCreate{value: val, isSet: true}
}

func (v NullableRequestProjectsCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestProjectsCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


