/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package convex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestProjectsUpdateStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestProjectsUpdateStats{}

// RequestProjectsUpdateStats struct for RequestProjectsUpdateStats
type RequestProjectsUpdateStats struct {
	Args RequestProjectsUpdateStatsArgs `json:"args"`
}

type _RequestProjectsUpdateStats RequestProjectsUpdateStats

// NewRequestProjectsUpdateStats instantiates a new RequestProjectsUpdateStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestProjectsUpdateStats(args RequestProjectsUpdateStatsArgs) *RequestProjectsUpdateStats {
	this := RequestProjectsUpdateStats{}
	this.Args = args
	return &this
}

// NewRequestProjectsUpdateStatsWithDefaults instantiates a new RequestProjectsUpdateStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestProjectsUpdateStatsWithDefaults() *RequestProjectsUpdateStats {
	this := RequestProjectsUpdateStats{}
	return &this
}

// GetArgs returns the Args field value
func (o *RequestProjectsUpdateStats) GetArgs() RequestProjectsUpdateStatsArgs {
	if o == nil {
		var ret RequestProjectsUpdateStatsArgs
		return ret
	}

	return o.Args
}

// GetArgsOk returns a tuple with the Args field value
// and a boolean to check if the value has been set.
func (o *RequestProjectsUpdateStats) GetArgsOk() (*RequestProjectsUpdateStatsArgs, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Args, true
}

// SetArgs sets field value
func (o *RequestProjectsUpdateStats) SetArgs(v RequestProjectsUpdateStatsArgs) {
	o.Args = v
}

func (o RequestProjectsUpdateStats) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestProjectsUpdateStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["args"] = o.Args
	return toSerialize, nil
}

func (o *RequestProjectsUpdateStats) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"args",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestProjectsUpdateStats := _RequestProjectsUpdateStats{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestProjectsUpdateStats)

	if err != nil {
		return err
	}

	*o = RequestProjectsUpdateStats(varRequestProjectsUpdateStats)

	return err
}

type NullableRequestProjectsUpdateStats struct {
	value *RequestProjectsUpdateStats
	isSet bool
}

func (v NullableRequestProjectsUpdateStats) Get() *RequestProjectsUpdateStats {
	return v.value
}

func (v *NullableRequestProjectsUpdateStats) Set(val *RequestProjectsUpdateStats) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestProjectsUpdateStats) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestProjectsUpdateStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestProjectsUpdateStats(val *RequestProjectsUpdateStats) *NullableRequestProjectsUpdateStats {
	return &NullableRequestProjectsUpdateStats{value: val, isSet: true}
}

func (v NullableRequestProjectsUpdateStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestProjectsUpdateStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


