/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package convex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestSettingsGetSettingsArgs type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestSettingsGetSettingsArgs{}

// RequestSettingsGetSettingsArgs struct for RequestSettingsGetSettingsArgs
type RequestSettingsGetSettingsArgs struct {
	UserId string `json:"userId"`
}

type _RequestSettingsGetSettingsArgs RequestSettingsGetSettingsArgs

// NewRequestSettingsGetSettingsArgs instantiates a new RequestSettingsGetSettingsArgs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestSettingsGetSettingsArgs(userId string) *RequestSettingsGetSettingsArgs {
	this := RequestSettingsGetSettingsArgs{}
	this.UserId = userId
	return &this
}

// NewRequestSettingsGetSettingsArgsWithDefaults instantiates a new RequestSettingsGetSettingsArgs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestSettingsGetSettingsArgsWithDefaults() *RequestSettingsGetSettingsArgs {
	this := RequestSettingsGetSettingsArgs{}
	return &this
}

// GetUserId returns the UserId field value
func (o *RequestSettingsGetSettingsArgs) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *RequestSettingsGetSettingsArgs) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *RequestSettingsGetSettingsArgs) SetUserId(v string) {
	o.UserId = v
}

func (o RequestSettingsGetSettingsArgs) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestSettingsGetSettingsArgs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["userId"] = o.UserId
	return toSerialize, nil
}

func (o *RequestSettingsGetSettingsArgs) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"userId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestSettingsGetSettingsArgs := _RequestSettingsGetSettingsArgs{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestSettingsGetSettingsArgs)

	if err != nil {
		return err
	}

	*o = RequestSettingsGetSettingsArgs(varRequestSettingsGetSettingsArgs)

	return err
}

type NullableRequestSettingsGetSettingsArgs struct {
	value *RequestSettingsGetSettingsArgs
	isSet bool
}

func (v NullableRequestSettingsGetSettingsArgs) Get() *RequestSettingsGetSettingsArgs {
	return v.value
}

func (v *NullableRequestSettingsGetSettingsArgs) Set(val *RequestSettingsGetSettingsArgs) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestSettingsGetSettingsArgs) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestSettingsGetSettingsArgs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestSettingsGetSettingsArgs(val *RequestSettingsGetSettingsArgs) *NullableRequestSettingsGetSettingsArgs {
	return &NullableRequestSettingsGetSettingsArgs{value: val, isSet: true}
}

func (v NullableRequestSettingsGetSettingsArgs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestSettingsGetSettingsArgs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


