/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package convex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestTasksUpdatePosition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestTasksUpdatePosition{}

// RequestTasksUpdatePosition struct for RequestTasksUpdatePosition
type RequestTasksUpdatePosition struct {
	Args RequestProjectsUpdatePositionArgs `json:"args"`
}

type _RequestTasksUpdatePosition RequestTasksUpdatePosition

// NewRequestTasksUpdatePosition instantiates a new RequestTasksUpdatePosition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestTasksUpdatePosition(args RequestProjectsUpdatePositionArgs) *RequestTasksUpdatePosition {
	this := RequestTasksUpdatePosition{}
	this.Args = args
	return &this
}

// NewRequestTasksUpdatePositionWithDefaults instantiates a new RequestTasksUpdatePosition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestTasksUpdatePositionWithDefaults() *RequestTasksUpdatePosition {
	this := RequestTasksUpdatePosition{}
	return &this
}

// GetArgs returns the Args field value
func (o *RequestTasksUpdatePosition) GetArgs() RequestProjectsUpdatePositionArgs {
	if o == nil {
		var ret RequestProjectsUpdatePositionArgs
		return ret
	}

	return o.Args
}

// GetArgsOk returns a tuple with the Args field value
// and a boolean to check if the value has been set.
func (o *RequestTasksUpdatePosition) GetArgsOk() (*RequestProjectsUpdatePositionArgs, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Args, true
}

// SetArgs sets field value
func (o *RequestTasksUpdatePosition) SetArgs(v RequestProjectsUpdatePositionArgs) {
	o.Args = v
}

func (o RequestTasksUpdatePosition) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestTasksUpdatePosition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["args"] = o.Args
	return toSerialize, nil
}

func (o *RequestTasksUpdatePosition) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"args",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestTasksUpdatePosition := _RequestTasksUpdatePosition{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestTasksUpdatePosition)

	if err != nil {
		return err
	}

	*o = RequestTasksUpdatePosition(varRequestTasksUpdatePosition)

	return err
}

type NullableRequestTasksUpdatePosition struct {
	value *RequestTasksUpdatePosition
	isSet bool
}

func (v NullableRequestTasksUpdatePosition) Get() *RequestTasksUpdatePosition {
	return v.value
}

func (v *NullableRequestTasksUpdatePosition) Set(val *RequestTasksUpdatePosition) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestTasksUpdatePosition) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestTasksUpdatePosition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestTasksUpdatePosition(val *RequestTasksUpdatePosition) *NullableRequestTasksUpdatePosition {
	return &NullableRequestTasksUpdatePosition{value: val, isSet: true}
}

func (v NullableRequestTasksUpdatePosition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestTasksUpdatePosition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


