/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package convex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestAgentsCreateArgs type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestAgentsCreateArgs{}

// RequestAgentsCreateArgs struct for RequestAgentsCreateArgs
type RequestAgentsCreateArgs struct {
	Capabilities []string `json:"capabilities"`
	Description string `json:"description"`
	Name string `json:"name"`
	Role RequestAgentsListByRoleArgsRole `json:"role"`
}

type _RequestAgentsCreateArgs RequestAgentsCreateArgs

// NewRequestAgentsCreateArgs instantiates a new RequestAgentsCreateArgs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestAgentsCreateArgs(capabilities []string, description string, name string, role RequestAgentsListByRoleArgsRole) *RequestAgentsCreateArgs {
	this := RequestAgentsCreateArgs{}
	this.Capabilities = capabilities
	this.Description = description
	this.Name = name
	this.Role = role
	return &this
}

// NewRequestAgentsCreateArgsWithDefaults instantiates a new RequestAgentsCreateArgs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestAgentsCreateArgsWithDefaults() *RequestAgentsCreateArgs {
	this := RequestAgentsCreateArgs{}
	return &this
}

// GetCapabilities returns the Capabilities field value
func (o *RequestAgentsCreateArgs) GetCapabilities() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Capabilities
}

// GetCapabilitiesOk returns a tuple with the Capabilities field value
// and a boolean to check if the value has been set.
func (o *RequestAgentsCreateArgs) GetCapabilitiesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Capabilities, true
}

// SetCapabilities sets field value
func (o *RequestAgentsCreateArgs) SetCapabilities(v []string) {
	o.Capabilities = v
}

// GetDescription returns the Description field value
func (o *RequestAgentsCreateArgs) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *RequestAgentsCreateArgs) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *RequestAgentsCreateArgs) SetDescription(v string) {
	o.Description = v
}

// GetName returns the Name field value
func (o *RequestAgentsCreateArgs) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *RequestAgentsCreateArgs) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *RequestAgentsCreateArgs) SetName(v string) {
	o.Name = v
}

// GetRole returns the Role field value
func (o *RequestAgentsCreateArgs) GetRole() RequestAgentsListByRoleArgsRole {
	if o == nil {
		var ret RequestAgentsListByRoleArgsRole
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *RequestAgentsCreateArgs) GetRoleOk() (*RequestAgentsListByRoleArgsRole, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *RequestAgentsCreateArgs) SetRole(v RequestAgentsListByRoleArgsRole) {
	o.Role = v
}

func (o RequestAgentsCreateArgs) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestAgentsCreateArgs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["capabilities"] = o.Capabilities
	toSerialize["description"] = o.Description
	toSerialize["name"] = o.Name
	toSerialize["role"] = o.Role
	return toSerialize, nil
}

func (o *RequestAgentsCreateArgs) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"capabilities",
		"description",
		"name",
		"role",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestAgentsCreateArgs := _RequestAgentsCreateArgs{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestAgentsCreateArgs)

	if err != nil {
		return err
	}

	*o = RequestAgentsCreateArgs(varRequestAgentsCreateArgs)

	return err
}

type NullableRequestAgentsCreateArgs struct {
	value *RequestAgentsCreateArgs
	isSet bool
}

func (v NullableRequestAgentsCreateArgs) Get() *RequestAgentsCreateArgs {
	return v.value
}

func (v *NullableRequestAgentsCreateArgs) Set(val *RequestAgentsCreateArgs) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestAgentsCreateArgs) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestAgentsCreateArgs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestAgentsCreateArgs(val *RequestAgentsCreateArgs) *NullableRequestAgentsCreateArgs {
	return &NullableRequestAgentsCreateArgs{value: val, isSet: true}
}

func (v NullableRequestAgentsCreateArgs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestAgentsCreateArgs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


