/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package convex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestEventsCleanupOldEventsArgs type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestEventsCleanupOldEventsArgs{}

// RequestEventsCleanupOldEventsArgs struct for RequestEventsCleanupOldEventsArgs
type RequestEventsCleanupOldEventsArgs struct {
	OlderThan float32 `json:"olderThan"`
}

type _RequestEventsCleanupOldEventsArgs RequestEventsCleanupOldEventsArgs

// NewRequestEventsCleanupOldEventsArgs instantiates a new RequestEventsCleanupOldEventsArgs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestEventsCleanupOldEventsArgs(olderThan float32) *RequestEventsCleanupOldEventsArgs {
	this := RequestEventsCleanupOldEventsArgs{}
	this.OlderThan = olderThan
	return &this
}

// NewRequestEventsCleanupOldEventsArgsWithDefaults instantiates a new RequestEventsCleanupOldEventsArgs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestEventsCleanupOldEventsArgsWithDefaults() *RequestEventsCleanupOldEventsArgs {
	this := RequestEventsCleanupOldEventsArgs{}
	return &this
}

// GetOlderThan returns the OlderThan field value
func (o *RequestEventsCleanupOldEventsArgs) GetOlderThan() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.OlderThan
}

// GetOlderThanOk returns a tuple with the OlderThan field value
// and a boolean to check if the value has been set.
func (o *RequestEventsCleanupOldEventsArgs) GetOlderThanOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OlderThan, true
}

// SetOlderThan sets field value
func (o *RequestEventsCleanupOldEventsArgs) SetOlderThan(v float32) {
	o.OlderThan = v
}

func (o RequestEventsCleanupOldEventsArgs) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestEventsCleanupOldEventsArgs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["olderThan"] = o.OlderThan
	return toSerialize, nil
}

func (o *RequestEventsCleanupOldEventsArgs) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"olderThan",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestEventsCleanupOldEventsArgs := _RequestEventsCleanupOldEventsArgs{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestEventsCleanupOldEventsArgs)

	if err != nil {
		return err
	}

	*o = RequestEventsCleanupOldEventsArgs(varRequestEventsCleanupOldEventsArgs)

	return err
}

type NullableRequestEventsCleanupOldEventsArgs struct {
	value *RequestEventsCleanupOldEventsArgs
	isSet bool
}

func (v NullableRequestEventsCleanupOldEventsArgs) Get() *RequestEventsCleanupOldEventsArgs {
	return v.value
}

func (v *NullableRequestEventsCleanupOldEventsArgs) Set(val *RequestEventsCleanupOldEventsArgs) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestEventsCleanupOldEventsArgs) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestEventsCleanupOldEventsArgs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestEventsCleanupOldEventsArgs(val *RequestEventsCleanupOldEventsArgs) *NullableRequestEventsCleanupOldEventsArgs {
	return &NullableRequestEventsCleanupOldEventsArgs{value: val, isSet: true}
}

func (v NullableRequestEventsCleanupOldEventsArgs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestEventsCleanupOldEventsArgs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


