/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package convex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestAgentsCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestAgentsCreate{}

// RequestAgentsCreate struct for RequestAgentsCreate
type RequestAgentsCreate struct {
	Args RequestAgentsCreateArgs `json:"args"`
}

type _RequestAgentsCreate RequestAgentsCreate

// NewRequestAgentsCreate instantiates a new RequestAgentsCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestAgentsCreate(args RequestAgentsCreateArgs) *RequestAgentsCreate {
	this := RequestAgentsCreate{}
	this.Args = args
	return &this
}

// NewRequestAgentsCreateWithDefaults instantiates a new RequestAgentsCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestAgentsCreateWithDefaults() *RequestAgentsCreate {
	this := RequestAgentsCreate{}
	return &this
}

// GetArgs returns the Args field value
func (o *RequestAgentsCreate) GetArgs() RequestAgentsCreateArgs {
	if o == nil {
		var ret RequestAgentsCreateArgs
		return ret
	}

	return o.Args
}

// GetArgsOk returns a tuple with the Args field value
// and a boolean to check if the value has been set.
func (o *RequestAgentsCreate) GetArgsOk() (*RequestAgentsCreateArgs, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Args, true
}

// SetArgs sets field value
func (o *RequestAgentsCreate) SetArgs(v RequestAgentsCreateArgs) {
	o.Args = v
}

func (o RequestAgentsCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestAgentsCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["args"] = o.Args
	return toSerialize, nil
}

func (o *RequestAgentsCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"args",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestAgentsCreate := _RequestAgentsCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestAgentsCreate)

	if err != nil {
		return err
	}

	*o = RequestAgentsCreate(varRequestAgentsCreate)

	return err
}

type NullableRequestAgentsCreate struct {
	value *RequestAgentsCreate
	isSet bool
}

func (v NullableRequestAgentsCreate) Get() *RequestAgentsCreate {
	return v.value
}

func (v *NullableRequestAgentsCreate) Set(val *RequestAgentsCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestAgentsCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestAgentsCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestAgentsCreate(val *RequestAgentsCreate) *NullableRequestAgentsCreate {
	return &NullableRequestAgentsCreate{value: val, isSet: true}
}

func (v NullableRequestAgentsCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestAgentsCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


