/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package convex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestProjectsUpdateEditableFields type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestProjectsUpdateEditableFields{}

// RequestProjectsUpdateEditableFields struct for RequestProjectsUpdateEditableFields
type RequestProjectsUpdateEditableFields struct {
	Args RequestProjectsUpdateEditableFieldsArgs `json:"args"`
}

type _RequestProjectsUpdateEditableFields RequestProjectsUpdateEditableFields

// NewRequestProjectsUpdateEditableFields instantiates a new RequestProjectsUpdateEditableFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestProjectsUpdateEditableFields(args RequestProjectsUpdateEditableFieldsArgs) *RequestProjectsUpdateEditableFields {
	this := RequestProjectsUpdateEditableFields{}
	this.Args = args
	return &this
}

// NewRequestProjectsUpdateEditableFieldsWithDefaults instantiates a new RequestProjectsUpdateEditableFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestProjectsUpdateEditableFieldsWithDefaults() *RequestProjectsUpdateEditableFields {
	this := RequestProjectsUpdateEditableFields{}
	return &this
}

// GetArgs returns the Args field value
func (o *RequestProjectsUpdateEditableFields) GetArgs() RequestProjectsUpdateEditableFieldsArgs {
	if o == nil {
		var ret RequestProjectsUpdateEditableFieldsArgs
		return ret
	}

	return o.Args
}

// GetArgsOk returns a tuple with the Args field value
// and a boolean to check if the value has been set.
func (o *RequestProjectsUpdateEditableFields) GetArgsOk() (*RequestProjectsUpdateEditableFieldsArgs, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Args, true
}

// SetArgs sets field value
func (o *RequestProjectsUpdateEditableFields) SetArgs(v RequestProjectsUpdateEditableFieldsArgs) {
	o.Args = v
}

func (o RequestProjectsUpdateEditableFields) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestProjectsUpdateEditableFields) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["args"] = o.Args
	return toSerialize, nil
}

func (o *RequestProjectsUpdateEditableFields) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"args",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestProjectsUpdateEditableFields := _RequestProjectsUpdateEditableFields{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestProjectsUpdateEditableFields)

	if err != nil {
		return err
	}

	*o = RequestProjectsUpdateEditableFields(varRequestProjectsUpdateEditableFields)

	return err
}

type NullableRequestProjectsUpdateEditableFields struct {
	value *RequestProjectsUpdateEditableFields
	isSet bool
}

func (v NullableRequestProjectsUpdateEditableFields) Get() *RequestProjectsUpdateEditableFields {
	return v.value
}

func (v *NullableRequestProjectsUpdateEditableFields) Set(val *RequestProjectsUpdateEditableFields) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestProjectsUpdateEditableFields) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestProjectsUpdateEditableFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestProjectsUpdateEditableFields(val *RequestProjectsUpdateEditableFields) *NullableRequestProjectsUpdateEditableFields {
	return &NullableRequestProjectsUpdateEditableFields{value: val, isSet: true}
}

func (v NullableRequestProjectsUpdateEditableFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestProjectsUpdateEditableFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


