/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package convex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestProjectsUpdatePosition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestProjectsUpdatePosition{}

// RequestProjectsUpdatePosition struct for RequestProjectsUpdatePosition
type RequestProjectsUpdatePosition struct {
	Args RequestProjectsUpdatePositionArgs `json:"args"`
}

type _RequestProjectsUpdatePosition RequestProjectsUpdatePosition

// NewRequestProjectsUpdatePosition instantiates a new RequestProjectsUpdatePosition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestProjectsUpdatePosition(args RequestProjectsUpdatePositionArgs) *RequestProjectsUpdatePosition {
	this := RequestProjectsUpdatePosition{}
	this.Args = args
	return &this
}

// NewRequestProjectsUpdatePositionWithDefaults instantiates a new RequestProjectsUpdatePosition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestProjectsUpdatePositionWithDefaults() *RequestProjectsUpdatePosition {
	this := RequestProjectsUpdatePosition{}
	return &this
}

// GetArgs returns the Args field value
func (o *RequestProjectsUpdatePosition) GetArgs() RequestProjectsUpdatePositionArgs {
	if o == nil {
		var ret RequestProjectsUpdatePositionArgs
		return ret
	}

	return o.Args
}

// GetArgsOk returns a tuple with the Args field value
// and a boolean to check if the value has been set.
func (o *RequestProjectsUpdatePosition) GetArgsOk() (*RequestProjectsUpdatePositionArgs, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Args, true
}

// SetArgs sets field value
func (o *RequestProjectsUpdatePosition) SetArgs(v RequestProjectsUpdatePositionArgs) {
	o.Args = v
}

func (o RequestProjectsUpdatePosition) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestProjectsUpdatePosition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["args"] = o.Args
	return toSerialize, nil
}

func (o *RequestProjectsUpdatePosition) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"args",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestProjectsUpdatePosition := _RequestProjectsUpdatePosition{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestProjectsUpdatePosition)

	if err != nil {
		return err
	}

	*o = RequestProjectsUpdatePosition(varRequestProjectsUpdatePosition)

	return err
}

type NullableRequestProjectsUpdatePosition struct {
	value *RequestProjectsUpdatePosition
	isSet bool
}

func (v NullableRequestProjectsUpdatePosition) Get() *RequestProjectsUpdatePosition {
	return v.value
}

func (v *NullableRequestProjectsUpdatePosition) Set(val *RequestProjectsUpdatePosition) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestProjectsUpdatePosition) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestProjectsUpdatePosition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestProjectsUpdatePosition(val *RequestProjectsUpdatePosition) *NullableRequestProjectsUpdatePosition {
	return &NullableRequestProjectsUpdatePosition{value: val, isSet: true}
}

func (v NullableRequestProjectsUpdatePosition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestProjectsUpdatePosition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


