/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package convex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestTasksUpdateStateArgs type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestTasksUpdateStateArgs{}

// RequestTasksUpdateStateArgs struct for RequestTasksUpdateStateArgs
type RequestTasksUpdateStateArgs struct {
	Id string `json:"id"`
	State RequestTasksUpdateStateArgsState `json:"state"`
}

type _RequestTasksUpdateStateArgs RequestTasksUpdateStateArgs

// NewRequestTasksUpdateStateArgs instantiates a new RequestTasksUpdateStateArgs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestTasksUpdateStateArgs(id string, state RequestTasksUpdateStateArgsState) *RequestTasksUpdateStateArgs {
	this := RequestTasksUpdateStateArgs{}
	this.Id = id
	this.State = state
	return &this
}

// NewRequestTasksUpdateStateArgsWithDefaults instantiates a new RequestTasksUpdateStateArgs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestTasksUpdateStateArgsWithDefaults() *RequestTasksUpdateStateArgs {
	this := RequestTasksUpdateStateArgs{}
	return &this
}

// GetId returns the Id field value
func (o *RequestTasksUpdateStateArgs) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RequestTasksUpdateStateArgs) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RequestTasksUpdateStateArgs) SetId(v string) {
	o.Id = v
}

// GetState returns the State field value
func (o *RequestTasksUpdateStateArgs) GetState() RequestTasksUpdateStateArgsState {
	if o == nil {
		var ret RequestTasksUpdateStateArgsState
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *RequestTasksUpdateStateArgs) GetStateOk() (*RequestTasksUpdateStateArgsState, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *RequestTasksUpdateStateArgs) SetState(v RequestTasksUpdateStateArgsState) {
	o.State = v
}

func (o RequestTasksUpdateStateArgs) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestTasksUpdateStateArgs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["state"] = o.State
	return toSerialize, nil
}

func (o *RequestTasksUpdateStateArgs) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"state",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestTasksUpdateStateArgs := _RequestTasksUpdateStateArgs{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestTasksUpdateStateArgs)

	if err != nil {
		return err
	}

	*o = RequestTasksUpdateStateArgs(varRequestTasksUpdateStateArgs)

	return err
}

type NullableRequestTasksUpdateStateArgs struct {
	value *RequestTasksUpdateStateArgs
	isSet bool
}

func (v NullableRequestTasksUpdateStateArgs) Get() *RequestTasksUpdateStateArgs {
	return v.value
}

func (v *NullableRequestTasksUpdateStateArgs) Set(val *RequestTasksUpdateStateArgs) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestTasksUpdateStateArgs) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestTasksUpdateStateArgs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestTasksUpdateStateArgs(val *RequestTasksUpdateStateArgs) *NullableRequestTasksUpdateStateArgs {
	return &NullableRequestTasksUpdateStateArgs{value: val, isSet: true}
}

func (v NullableRequestTasksUpdateStateArgs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestTasksUpdateStateArgs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


