/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package convex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestTasksListRootTasks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestTasksListRootTasks{}

// RequestTasksListRootTasks struct for RequestTasksListRootTasks
type RequestTasksListRootTasks struct {
	Args RequestTasksListRootTasksArgs `json:"args"`
}

type _RequestTasksListRootTasks RequestTasksListRootTasks

// NewRequestTasksListRootTasks instantiates a new RequestTasksListRootTasks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestTasksListRootTasks(args RequestTasksListRootTasksArgs) *RequestTasksListRootTasks {
	this := RequestTasksListRootTasks{}
	this.Args = args
	return &this
}

// NewRequestTasksListRootTasksWithDefaults instantiates a new RequestTasksListRootTasks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestTasksListRootTasksWithDefaults() *RequestTasksListRootTasks {
	this := RequestTasksListRootTasks{}
	return &this
}

// GetArgs returns the Args field value
func (o *RequestTasksListRootTasks) GetArgs() RequestTasksListRootTasksArgs {
	if o == nil {
		var ret RequestTasksListRootTasksArgs
		return ret
	}

	return o.Args
}

// GetArgsOk returns a tuple with the Args field value
// and a boolean to check if the value has been set.
func (o *RequestTasksListRootTasks) GetArgsOk() (*RequestTasksListRootTasksArgs, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Args, true
}

// SetArgs sets field value
func (o *RequestTasksListRootTasks) SetArgs(v RequestTasksListRootTasksArgs) {
	o.Args = v
}

func (o RequestTasksListRootTasks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestTasksListRootTasks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["args"] = o.Args
	return toSerialize, nil
}

func (o *RequestTasksListRootTasks) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"args",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestTasksListRootTasks := _RequestTasksListRootTasks{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestTasksListRootTasks)

	if err != nil {
		return err
	}

	*o = RequestTasksListRootTasks(varRequestTasksListRootTasks)

	return err
}

type NullableRequestTasksListRootTasks struct {
	value *RequestTasksListRootTasks
	isSet bool
}

func (v NullableRequestTasksListRootTasks) Get() *RequestTasksListRootTasks {
	return v.value
}

func (v *NullableRequestTasksListRootTasks) Set(val *RequestTasksListRootTasks) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestTasksListRootTasks) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestTasksListRootTasks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestTasksListRootTasks(val *RequestTasksListRootTasks) *NullableRequestTasksListRootTasks {
	return &NullableRequestTasksListRootTasks{value: val, isSet: true}
}

func (v NullableRequestTasksListRootTasks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestTasksListRootTasks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


