/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package convex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestTasksUpdateEditableFields type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestTasksUpdateEditableFields{}

// RequestTasksUpdateEditableFields struct for RequestTasksUpdateEditableFields
type RequestTasksUpdateEditableFields struct {
	Args RequestProjectsUpdateEditableFieldsArgs `json:"args"`
}

type _RequestTasksUpdateEditableFields RequestTasksUpdateEditableFields

// NewRequestTasksUpdateEditableFields instantiates a new RequestTasksUpdateEditableFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestTasksUpdateEditableFields(args RequestProjectsUpdateEditableFieldsArgs) *RequestTasksUpdateEditableFields {
	this := RequestTasksUpdateEditableFields{}
	this.Args = args
	return &this
}

// NewRequestTasksUpdateEditableFieldsWithDefaults instantiates a new RequestTasksUpdateEditableFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestTasksUpdateEditableFieldsWithDefaults() *RequestTasksUpdateEditableFields {
	this := RequestTasksUpdateEditableFields{}
	return &this
}

// GetArgs returns the Args field value
func (o *RequestTasksUpdateEditableFields) GetArgs() RequestProjectsUpdateEditableFieldsArgs {
	if o == nil {
		var ret RequestProjectsUpdateEditableFieldsArgs
		return ret
	}

	return o.Args
}

// GetArgsOk returns a tuple with the Args field value
// and a boolean to check if the value has been set.
func (o *RequestTasksUpdateEditableFields) GetArgsOk() (*RequestProjectsUpdateEditableFieldsArgs, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Args, true
}

// SetArgs sets field value
func (o *RequestTasksUpdateEditableFields) SetArgs(v RequestProjectsUpdateEditableFieldsArgs) {
	o.Args = v
}

func (o RequestTasksUpdateEditableFields) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestTasksUpdateEditableFields) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["args"] = o.Args
	return toSerialize, nil
}

func (o *RequestTasksUpdateEditableFields) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"args",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestTasksUpdateEditableFields := _RequestTasksUpdateEditableFields{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestTasksUpdateEditableFields)

	if err != nil {
		return err
	}

	*o = RequestTasksUpdateEditableFields(varRequestTasksUpdateEditableFields)

	return err
}

type NullableRequestTasksUpdateEditableFields struct {
	value *RequestTasksUpdateEditableFields
	isSet bool
}

func (v NullableRequestTasksUpdateEditableFields) Get() *RequestTasksUpdateEditableFields {
	return v.value
}

func (v *NullableRequestTasksUpdateEditableFields) Set(val *RequestTasksUpdateEditableFields) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestTasksUpdateEditableFields) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestTasksUpdateEditableFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestTasksUpdateEditableFields(val *RequestTasksUpdateEditableFields) *NullableRequestTasksUpdateEditableFields {
	return &NullableRequestTasksUpdateEditableFields{value: val, isSet: true}
}

func (v NullableRequestTasksUpdateEditableFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestTasksUpdateEditableFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


