/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package convex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestTasksRemove type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestTasksRemove{}

// RequestTasksRemove struct for RequestTasksRemove
type RequestTasksRemove struct {
	Args RequestAgentsGetArgs `json:"args"`
}

type _RequestTasksRemove RequestTasksRemove

// NewRequestTasksRemove instantiates a new RequestTasksRemove object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestTasksRemove(args RequestAgentsGetArgs) *RequestTasksRemove {
	this := RequestTasksRemove{}
	this.Args = args
	return &this
}

// NewRequestTasksRemoveWithDefaults instantiates a new RequestTasksRemove object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestTasksRemoveWithDefaults() *RequestTasksRemove {
	this := RequestTasksRemove{}
	return &this
}

// GetArgs returns the Args field value
func (o *RequestTasksRemove) GetArgs() RequestAgentsGetArgs {
	if o == nil {
		var ret RequestAgentsGetArgs
		return ret
	}

	return o.Args
}

// GetArgsOk returns a tuple with the Args field value
// and a boolean to check if the value has been set.
func (o *RequestTasksRemove) GetArgsOk() (*RequestAgentsGetArgs, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Args, true
}

// SetArgs sets field value
func (o *RequestTasksRemove) SetArgs(v RequestAgentsGetArgs) {
	o.Args = v
}

func (o RequestTasksRemove) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestTasksRemove) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["args"] = o.Args
	return toSerialize, nil
}

func (o *RequestTasksRemove) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"args",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestTasksRemove := _RequestTasksRemove{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestTasksRemove)

	if err != nil {
		return err
	}

	*o = RequestTasksRemove(varRequestTasksRemove)

	return err
}

type NullableRequestTasksRemove struct {
	value *RequestTasksRemove
	isSet bool
}

func (v NullableRequestTasksRemove) Get() *RequestTasksRemove {
	return v.value
}

func (v *NullableRequestTasksRemove) Set(val *RequestTasksRemove) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestTasksRemove) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestTasksRemove) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestTasksRemove(val *RequestTasksRemove) *NullableRequestTasksRemove {
	return &NullableRequestTasksRemove{value: val, isSet: true}
}

func (v NullableRequestTasksRemove) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestTasksRemove) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


