/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package convex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestAgentsList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestAgentsList{}

// RequestAgentsList struct for RequestAgentsList
type RequestAgentsList struct {
	Args map[string]interface{} `json:"args"`
}

type _RequestAgentsList RequestAgentsList

// NewRequestAgentsList instantiates a new RequestAgentsList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestAgentsList(args map[string]interface{}) *RequestAgentsList {
	this := RequestAgentsList{}
	this.Args = args
	return &this
}

// NewRequestAgentsListWithDefaults instantiates a new RequestAgentsList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestAgentsListWithDefaults() *RequestAgentsList {
	this := RequestAgentsList{}
	return &this
}

// GetArgs returns the Args field value
func (o *RequestAgentsList) GetArgs() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Args
}

// GetArgsOk returns a tuple with the Args field value
// and a boolean to check if the value has been set.
func (o *RequestAgentsList) GetArgsOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Args, true
}

// SetArgs sets field value
func (o *RequestAgentsList) SetArgs(v map[string]interface{}) {
	o.Args = v
}

func (o RequestAgentsList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestAgentsList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["args"] = o.Args
	return toSerialize, nil
}

func (o *RequestAgentsList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"args",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestAgentsList := _RequestAgentsList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestAgentsList)

	if err != nil {
		return err
	}

	*o = RequestAgentsList(varRequestAgentsList)

	return err
}

type NullableRequestAgentsList struct {
	value *RequestAgentsList
	isSet bool
}

func (v NullableRequestAgentsList) Get() *RequestAgentsList {
	return v.value
}

func (v *NullableRequestAgentsList) Set(val *RequestAgentsList) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestAgentsList) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestAgentsList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestAgentsList(val *RequestAgentsList) *NullableRequestAgentsList {
	return &NullableRequestAgentsList{value: val, isSet: true}
}

func (v NullableRequestAgentsList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestAgentsList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


