/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package convex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestEventsCleanupOldEvents type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestEventsCleanupOldEvents{}

// RequestEventsCleanupOldEvents struct for RequestEventsCleanupOldEvents
type RequestEventsCleanupOldEvents struct {
	Args RequestEventsCleanupOldEventsArgs `json:"args"`
}

type _RequestEventsCleanupOldEvents RequestEventsCleanupOldEvents

// NewRequestEventsCleanupOldEvents instantiates a new RequestEventsCleanupOldEvents object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestEventsCleanupOldEvents(args RequestEventsCleanupOldEventsArgs) *RequestEventsCleanupOldEvents {
	this := RequestEventsCleanupOldEvents{}
	this.Args = args
	return &this
}

// NewRequestEventsCleanupOldEventsWithDefaults instantiates a new RequestEventsCleanupOldEvents object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestEventsCleanupOldEventsWithDefaults() *RequestEventsCleanupOldEvents {
	this := RequestEventsCleanupOldEvents{}
	return &this
}

// GetArgs returns the Args field value
func (o *RequestEventsCleanupOldEvents) GetArgs() RequestEventsCleanupOldEventsArgs {
	if o == nil {
		var ret RequestEventsCleanupOldEventsArgs
		return ret
	}

	return o.Args
}

// GetArgsOk returns a tuple with the Args field value
// and a boolean to check if the value has been set.
func (o *RequestEventsCleanupOldEvents) GetArgsOk() (*RequestEventsCleanupOldEventsArgs, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Args, true
}

// SetArgs sets field value
func (o *RequestEventsCleanupOldEvents) SetArgs(v RequestEventsCleanupOldEventsArgs) {
	o.Args = v
}

func (o RequestEventsCleanupOldEvents) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestEventsCleanupOldEvents) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["args"] = o.Args
	return toSerialize, nil
}

func (o *RequestEventsCleanupOldEvents) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"args",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestEventsCleanupOldEvents := _RequestEventsCleanupOldEvents{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestEventsCleanupOldEvents)

	if err != nil {
		return err
	}

	*o = RequestEventsCleanupOldEvents(varRequestEventsCleanupOldEvents)

	return err
}

type NullableRequestEventsCleanupOldEvents struct {
	value *RequestEventsCleanupOldEvents
	isSet bool
}

func (v NullableRequestEventsCleanupOldEvents) Get() *RequestEventsCleanupOldEvents {
	return v.value
}

func (v *NullableRequestEventsCleanupOldEvents) Set(val *RequestEventsCleanupOldEvents) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestEventsCleanupOldEvents) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestEventsCleanupOldEvents) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestEventsCleanupOldEvents(val *RequestEventsCleanupOldEvents) *NullableRequestEventsCleanupOldEvents {
	return &NullableRequestEventsCleanupOldEvents{value: val, isSet: true}
}

func (v NullableRequestEventsCleanupOldEvents) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestEventsCleanupOldEvents) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


