/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package convex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestEventsEmitEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestEventsEmitEvent{}

// RequestEventsEmitEvent struct for RequestEventsEmitEvent
type RequestEventsEmitEvent struct {
	Args RequestEventsEmitEventArgs `json:"args"`
}

type _RequestEventsEmitEvent RequestEventsEmitEvent

// NewRequestEventsEmitEvent instantiates a new RequestEventsEmitEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestEventsEmitEvent(args RequestEventsEmitEventArgs) *RequestEventsEmitEvent {
	this := RequestEventsEmitEvent{}
	this.Args = args
	return &this
}

// NewRequestEventsEmitEventWithDefaults instantiates a new RequestEventsEmitEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestEventsEmitEventWithDefaults() *RequestEventsEmitEvent {
	this := RequestEventsEmitEvent{}
	return &this
}

// GetArgs returns the Args field value
func (o *RequestEventsEmitEvent) GetArgs() RequestEventsEmitEventArgs {
	if o == nil {
		var ret RequestEventsEmitEventArgs
		return ret
	}

	return o.Args
}

// GetArgsOk returns a tuple with the Args field value
// and a boolean to check if the value has been set.
func (o *RequestEventsEmitEvent) GetArgsOk() (*RequestEventsEmitEventArgs, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Args, true
}

// SetArgs sets field value
func (o *RequestEventsEmitEvent) SetArgs(v RequestEventsEmitEventArgs) {
	o.Args = v
}

func (o RequestEventsEmitEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestEventsEmitEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["args"] = o.Args
	return toSerialize, nil
}

func (o *RequestEventsEmitEvent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"args",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestEventsEmitEvent := _RequestEventsEmitEvent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestEventsEmitEvent)

	if err != nil {
		return err
	}

	*o = RequestEventsEmitEvent(varRequestEventsEmitEvent)

	return err
}

type NullableRequestEventsEmitEvent struct {
	value *RequestEventsEmitEvent
	isSet bool
}

func (v NullableRequestEventsEmitEvent) Get() *RequestEventsEmitEvent {
	return v.value
}

func (v *NullableRequestEventsEmitEvent) Set(val *RequestEventsEmitEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestEventsEmitEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestEventsEmitEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestEventsEmitEvent(val *RequestEventsEmitEvent) *NullableRequestEventsEmitEvent {
	return &NullableRequestEventsEmitEvent{value: val, isSet: true}
}

func (v NullableRequestEventsEmitEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestEventsEmitEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


