/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package convex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestTasksCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestTasksCreate{}

// RequestTasksCreate struct for RequestTasksCreate
type RequestTasksCreate struct {
	Args RequestTasksCreateArgs `json:"args"`
}

type _RequestTasksCreate RequestTasksCreate

// NewRequestTasksCreate instantiates a new RequestTasksCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestTasksCreate(args RequestTasksCreateArgs) *RequestTasksCreate {
	this := RequestTasksCreate{}
	this.Args = args
	return &this
}

// NewRequestTasksCreateWithDefaults instantiates a new RequestTasksCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestTasksCreateWithDefaults() *RequestTasksCreate {
	this := RequestTasksCreate{}
	return &this
}

// GetArgs returns the Args field value
func (o *RequestTasksCreate) GetArgs() RequestTasksCreateArgs {
	if o == nil {
		var ret RequestTasksCreateArgs
		return ret
	}

	return o.Args
}

// GetArgsOk returns a tuple with the Args field value
// and a boolean to check if the value has been set.
func (o *RequestTasksCreate) GetArgsOk() (*RequestTasksCreateArgs, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Args, true
}

// SetArgs sets field value
func (o *RequestTasksCreate) SetArgs(v RequestTasksCreateArgs) {
	o.Args = v
}

func (o RequestTasksCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestTasksCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["args"] = o.Args
	return toSerialize, nil
}

func (o *RequestTasksCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"args",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestTasksCreate := _RequestTasksCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestTasksCreate)

	if err != nil {
		return err
	}

	*o = RequestTasksCreate(varRequestTasksCreate)

	return err
}

type NullableRequestTasksCreate struct {
	value *RequestTasksCreate
	isSet bool
}

func (v NullableRequestTasksCreate) Get() *RequestTasksCreate {
	return v.value
}

func (v *NullableRequestTasksCreate) Set(val *RequestTasksCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestTasksCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestTasksCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestTasksCreate(val *RequestTasksCreate) *NullableRequestTasksCreate {
	return &NullableRequestTasksCreate{value: val, isSet: true}
}

func (v NullableRequestTasksCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestTasksCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


