/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package convex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestSettingsUpdateThemeArgs type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestSettingsUpdateThemeArgs{}

// RequestSettingsUpdateThemeArgs struct for RequestSettingsUpdateThemeArgs
type RequestSettingsUpdateThemeArgs struct {
	Theme RequestSettingsUpdateSettingsArgsTheme `json:"theme"`
	UserId string `json:"userId"`
}

type _RequestSettingsUpdateThemeArgs RequestSettingsUpdateThemeArgs

// NewRequestSettingsUpdateThemeArgs instantiates a new RequestSettingsUpdateThemeArgs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestSettingsUpdateThemeArgs(theme RequestSettingsUpdateSettingsArgsTheme, userId string) *RequestSettingsUpdateThemeArgs {
	this := RequestSettingsUpdateThemeArgs{}
	this.Theme = theme
	this.UserId = userId
	return &this
}

// NewRequestSettingsUpdateThemeArgsWithDefaults instantiates a new RequestSettingsUpdateThemeArgs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestSettingsUpdateThemeArgsWithDefaults() *RequestSettingsUpdateThemeArgs {
	this := RequestSettingsUpdateThemeArgs{}
	return &this
}

// GetTheme returns the Theme field value
func (o *RequestSettingsUpdateThemeArgs) GetTheme() RequestSettingsUpdateSettingsArgsTheme {
	if o == nil {
		var ret RequestSettingsUpdateSettingsArgsTheme
		return ret
	}

	return o.Theme
}

// GetThemeOk returns a tuple with the Theme field value
// and a boolean to check if the value has been set.
func (o *RequestSettingsUpdateThemeArgs) GetThemeOk() (*RequestSettingsUpdateSettingsArgsTheme, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Theme, true
}

// SetTheme sets field value
func (o *RequestSettingsUpdateThemeArgs) SetTheme(v RequestSettingsUpdateSettingsArgsTheme) {
	o.Theme = v
}

// GetUserId returns the UserId field value
func (o *RequestSettingsUpdateThemeArgs) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *RequestSettingsUpdateThemeArgs) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *RequestSettingsUpdateThemeArgs) SetUserId(v string) {
	o.UserId = v
}

func (o RequestSettingsUpdateThemeArgs) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestSettingsUpdateThemeArgs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["theme"] = o.Theme
	toSerialize["userId"] = o.UserId
	return toSerialize, nil
}

func (o *RequestSettingsUpdateThemeArgs) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"theme",
		"userId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestSettingsUpdateThemeArgs := _RequestSettingsUpdateThemeArgs{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestSettingsUpdateThemeArgs)

	if err != nil {
		return err
	}

	*o = RequestSettingsUpdateThemeArgs(varRequestSettingsUpdateThemeArgs)

	return err
}

type NullableRequestSettingsUpdateThemeArgs struct {
	value *RequestSettingsUpdateThemeArgs
	isSet bool
}

func (v NullableRequestSettingsUpdateThemeArgs) Get() *RequestSettingsUpdateThemeArgs {
	return v.value
}

func (v *NullableRequestSettingsUpdateThemeArgs) Set(val *RequestSettingsUpdateThemeArgs) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestSettingsUpdateThemeArgs) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestSettingsUpdateThemeArgs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestSettingsUpdateThemeArgs(val *RequestSettingsUpdateThemeArgs) *NullableRequestSettingsUpdateThemeArgs {
	return &NullableRequestSettingsUpdateThemeArgs{value: val, isSet: true}
}

func (v NullableRequestSettingsUpdateThemeArgs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestSettingsUpdateThemeArgs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


