/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package convex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestAgentsGet type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestAgentsGet{}

// RequestAgentsGet struct for RequestAgentsGet
type RequestAgentsGet struct {
	Args RequestAgentsGetArgs `json:"args"`
}

type _RequestAgentsGet RequestAgentsGet

// NewRequestAgentsGet instantiates a new RequestAgentsGet object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestAgentsGet(args RequestAgentsGetArgs) *RequestAgentsGet {
	this := RequestAgentsGet{}
	this.Args = args
	return &this
}

// NewRequestAgentsGetWithDefaults instantiates a new RequestAgentsGet object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestAgentsGetWithDefaults() *RequestAgentsGet {
	this := RequestAgentsGet{}
	return &this
}

// GetArgs returns the Args field value
func (o *RequestAgentsGet) GetArgs() RequestAgentsGetArgs {
	if o == nil {
		var ret RequestAgentsGetArgs
		return ret
	}

	return o.Args
}

// GetArgsOk returns a tuple with the Args field value
// and a boolean to check if the value has been set.
func (o *RequestAgentsGet) GetArgsOk() (*RequestAgentsGetArgs, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Args, true
}

// SetArgs sets field value
func (o *RequestAgentsGet) SetArgs(v RequestAgentsGetArgs) {
	o.Args = v
}

func (o RequestAgentsGet) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestAgentsGet) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["args"] = o.Args
	return toSerialize, nil
}

func (o *RequestAgentsGet) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"args",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestAgentsGet := _RequestAgentsGet{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestAgentsGet)

	if err != nil {
		return err
	}

	*o = RequestAgentsGet(varRequestAgentsGet)

	return err
}

type NullableRequestAgentsGet struct {
	value *RequestAgentsGet
	isSet bool
}

func (v NullableRequestAgentsGet) Get() *RequestAgentsGet {
	return v.value
}

func (v *NullableRequestAgentsGet) Set(val *RequestAgentsGet) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestAgentsGet) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestAgentsGet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestAgentsGet(val *RequestAgentsGet) *NullableRequestAgentsGet {
	return &NullableRequestAgentsGet{value: val, isSet: true}
}

func (v NullableRequestAgentsGet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestAgentsGet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


