/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package convex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestSettingsGetSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestSettingsGetSettings{}

// RequestSettingsGetSettings struct for RequestSettingsGetSettings
type RequestSettingsGetSettings struct {
	Args RequestSettingsGetSettingsArgs `json:"args"`
}

type _RequestSettingsGetSettings RequestSettingsGetSettings

// NewRequestSettingsGetSettings instantiates a new RequestSettingsGetSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestSettingsGetSettings(args RequestSettingsGetSettingsArgs) *RequestSettingsGetSettings {
	this := RequestSettingsGetSettings{}
	this.Args = args
	return &this
}

// NewRequestSettingsGetSettingsWithDefaults instantiates a new RequestSettingsGetSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestSettingsGetSettingsWithDefaults() *RequestSettingsGetSettings {
	this := RequestSettingsGetSettings{}
	return &this
}

// GetArgs returns the Args field value
func (o *RequestSettingsGetSettings) GetArgs() RequestSettingsGetSettingsArgs {
	if o == nil {
		var ret RequestSettingsGetSettingsArgs
		return ret
	}

	return o.Args
}

// GetArgsOk returns a tuple with the Args field value
// and a boolean to check if the value has been set.
func (o *RequestSettingsGetSettings) GetArgsOk() (*RequestSettingsGetSettingsArgs, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Args, true
}

// SetArgs sets field value
func (o *RequestSettingsGetSettings) SetArgs(v RequestSettingsGetSettingsArgs) {
	o.Args = v
}

func (o RequestSettingsGetSettings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestSettingsGetSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["args"] = o.Args
	return toSerialize, nil
}

func (o *RequestSettingsGetSettings) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"args",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestSettingsGetSettings := _RequestSettingsGetSettings{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestSettingsGetSettings)

	if err != nil {
		return err
	}

	*o = RequestSettingsGetSettings(varRequestSettingsGetSettings)

	return err
}

type NullableRequestSettingsGetSettings struct {
	value *RequestSettingsGetSettings
	isSet bool
}

func (v NullableRequestSettingsGetSettings) Get() *RequestSettingsGetSettings {
	return v.value
}

func (v *NullableRequestSettingsGetSettings) Set(val *RequestSettingsGetSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestSettingsGetSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestSettingsGetSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestSettingsGetSettings(val *RequestSettingsGetSettings) *NullableRequestSettingsGetSettings {
	return &NullableRequestSettingsGetSettings{value: val, isSet: true}
}

func (v NullableRequestSettingsGetSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestSettingsGetSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


