/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package convex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestAgentsListByRole type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestAgentsListByRole{}

// RequestAgentsListByRole struct for RequestAgentsListByRole
type RequestAgentsListByRole struct {
	Args RequestAgentsListByRoleArgs `json:"args"`
}

type _RequestAgentsListByRole RequestAgentsListByRole

// NewRequestAgentsListByRole instantiates a new RequestAgentsListByRole object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestAgentsListByRole(args RequestAgentsListByRoleArgs) *RequestAgentsListByRole {
	this := RequestAgentsListByRole{}
	this.Args = args
	return &this
}

// NewRequestAgentsListByRoleWithDefaults instantiates a new RequestAgentsListByRole object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestAgentsListByRoleWithDefaults() *RequestAgentsListByRole {
	this := RequestAgentsListByRole{}
	return &this
}

// GetArgs returns the Args field value
func (o *RequestAgentsListByRole) GetArgs() RequestAgentsListByRoleArgs {
	if o == nil {
		var ret RequestAgentsListByRoleArgs
		return ret
	}

	return o.Args
}

// GetArgsOk returns a tuple with the Args field value
// and a boolean to check if the value has been set.
func (o *RequestAgentsListByRole) GetArgsOk() (*RequestAgentsListByRoleArgs, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Args, true
}

// SetArgs sets field value
func (o *RequestAgentsListByRole) SetArgs(v RequestAgentsListByRoleArgs) {
	o.Args = v
}

func (o RequestAgentsListByRole) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestAgentsListByRole) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["args"] = o.Args
	return toSerialize, nil
}

func (o *RequestAgentsListByRole) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"args",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestAgentsListByRole := _RequestAgentsListByRole{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestAgentsListByRole)

	if err != nil {
		return err
	}

	*o = RequestAgentsListByRole(varRequestAgentsListByRole)

	return err
}

type NullableRequestAgentsListByRole struct {
	value *RequestAgentsListByRole
	isSet bool
}

func (v NullableRequestAgentsListByRole) Get() *RequestAgentsListByRole {
	return v.value
}

func (v *NullableRequestAgentsListByRole) Set(val *RequestAgentsListByRole) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestAgentsListByRole) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestAgentsListByRole) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestAgentsListByRole(val *RequestAgentsListByRole) *NullableRequestAgentsListByRole {
	return &NullableRequestAgentsListByRole{value: val, isSet: true}
}

func (v NullableRequestAgentsListByRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestAgentsListByRole) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


