/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package convex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestTasksUpdateState type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestTasksUpdateState{}

// RequestTasksUpdateState struct for RequestTasksUpdateState
type RequestTasksUpdateState struct {
	Args RequestTasksUpdateStateArgs `json:"args"`
}

type _RequestTasksUpdateState RequestTasksUpdateState

// NewRequestTasksUpdateState instantiates a new RequestTasksUpdateState object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestTasksUpdateState(args RequestTasksUpdateStateArgs) *RequestTasksUpdateState {
	this := RequestTasksUpdateState{}
	this.Args = args
	return &this
}

// NewRequestTasksUpdateStateWithDefaults instantiates a new RequestTasksUpdateState object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestTasksUpdateStateWithDefaults() *RequestTasksUpdateState {
	this := RequestTasksUpdateState{}
	return &this
}

// GetArgs returns the Args field value
func (o *RequestTasksUpdateState) GetArgs() RequestTasksUpdateStateArgs {
	if o == nil {
		var ret RequestTasksUpdateStateArgs
		return ret
	}

	return o.Args
}

// GetArgsOk returns a tuple with the Args field value
// and a boolean to check if the value has been set.
func (o *RequestTasksUpdateState) GetArgsOk() (*RequestTasksUpdateStateArgs, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Args, true
}

// SetArgs sets field value
func (o *RequestTasksUpdateState) SetArgs(v RequestTasksUpdateStateArgs) {
	o.Args = v
}

func (o RequestTasksUpdateState) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestTasksUpdateState) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["args"] = o.Args
	return toSerialize, nil
}

func (o *RequestTasksUpdateState) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"args",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestTasksUpdateState := _RequestTasksUpdateState{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestTasksUpdateState)

	if err != nil {
		return err
	}

	*o = RequestTasksUpdateState(varRequestTasksUpdateState)

	return err
}

type NullableRequestTasksUpdateState struct {
	value *RequestTasksUpdateState
	isSet bool
}

func (v NullableRequestTasksUpdateState) Get() *RequestTasksUpdateState {
	return v.value
}

func (v *NullableRequestTasksUpdateState) Set(val *RequestTasksUpdateState) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestTasksUpdateState) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestTasksUpdateState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestTasksUpdateState(val *RequestTasksUpdateState) *NullableRequestTasksUpdateState {
	return &NullableRequestTasksUpdateState{value: val, isSet: true}
}

func (v NullableRequestTasksUpdateState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestTasksUpdateState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


