/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package convex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestEventsGetRecentEvents type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestEventsGetRecentEvents{}

// RequestEventsGetRecentEvents struct for RequestEventsGetRecentEvents
type RequestEventsGetRecentEvents struct {
	Args RequestEventsGetRecentEventsArgs `json:"args"`
}

type _RequestEventsGetRecentEvents RequestEventsGetRecentEvents

// NewRequestEventsGetRecentEvents instantiates a new RequestEventsGetRecentEvents object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestEventsGetRecentEvents(args RequestEventsGetRecentEventsArgs) *RequestEventsGetRecentEvents {
	this := RequestEventsGetRecentEvents{}
	this.Args = args
	return &this
}

// NewRequestEventsGetRecentEventsWithDefaults instantiates a new RequestEventsGetRecentEvents object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestEventsGetRecentEventsWithDefaults() *RequestEventsGetRecentEvents {
	this := RequestEventsGetRecentEvents{}
	return &this
}

// GetArgs returns the Args field value
func (o *RequestEventsGetRecentEvents) GetArgs() RequestEventsGetRecentEventsArgs {
	if o == nil {
		var ret RequestEventsGetRecentEventsArgs
		return ret
	}

	return o.Args
}

// GetArgsOk returns a tuple with the Args field value
// and a boolean to check if the value has been set.
func (o *RequestEventsGetRecentEvents) GetArgsOk() (*RequestEventsGetRecentEventsArgs, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Args, true
}

// SetArgs sets field value
func (o *RequestEventsGetRecentEvents) SetArgs(v RequestEventsGetRecentEventsArgs) {
	o.Args = v
}

func (o RequestEventsGetRecentEvents) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestEventsGetRecentEvents) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["args"] = o.Args
	return toSerialize, nil
}

func (o *RequestEventsGetRecentEvents) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"args",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestEventsGetRecentEvents := _RequestEventsGetRecentEvents{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestEventsGetRecentEvents)

	if err != nil {
		return err
	}

	*o = RequestEventsGetRecentEvents(varRequestEventsGetRecentEvents)

	return err
}

type NullableRequestEventsGetRecentEvents struct {
	value *RequestEventsGetRecentEvents
	isSet bool
}

func (v NullableRequestEventsGetRecentEvents) Get() *RequestEventsGetRecentEvents {
	return v.value
}

func (v *NullableRequestEventsGetRecentEvents) Set(val *RequestEventsGetRecentEvents) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestEventsGetRecentEvents) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestEventsGetRecentEvents) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestEventsGetRecentEvents(val *RequestEventsGetRecentEvents) *NullableRequestEventsGetRecentEvents {
	return &NullableRequestEventsGetRecentEvents{value: val, isSet: true}
}

func (v NullableRequestEventsGetRecentEvents) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestEventsGetRecentEvents) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


