/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package convex

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// RequestSettingsUpdateSettingsArgsTheme - struct for RequestSettingsUpdateSettingsArgsTheme
type RequestSettingsUpdateSettingsArgsTheme struct {
	String *string
}

// stringAsRequestSettingsUpdateSettingsArgsTheme is a convenience function that returns string wrapped in RequestSettingsUpdateSettingsArgsTheme
func StringAsRequestSettingsUpdateSettingsArgsTheme(v *string) RequestSettingsUpdateSettingsArgsTheme {
	return RequestSettingsUpdateSettingsArgsTheme{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *RequestSettingsUpdateSettingsArgsTheme) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(RequestSettingsUpdateSettingsArgsTheme)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(RequestSettingsUpdateSettingsArgsTheme)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src RequestSettingsUpdateSettingsArgsTheme) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *RequestSettingsUpdateSettingsArgsTheme) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj RequestSettingsUpdateSettingsArgsTheme) GetActualInstanceValue() (interface{}) {
	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableRequestSettingsUpdateSettingsArgsTheme struct {
	value *RequestSettingsUpdateSettingsArgsTheme
	isSet bool
}

func (v NullableRequestSettingsUpdateSettingsArgsTheme) Get() *RequestSettingsUpdateSettingsArgsTheme {
	return v.value
}

func (v *NullableRequestSettingsUpdateSettingsArgsTheme) Set(val *RequestSettingsUpdateSettingsArgsTheme) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestSettingsUpdateSettingsArgsTheme) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestSettingsUpdateSettingsArgsTheme) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestSettingsUpdateSettingsArgsTheme(val *RequestSettingsUpdateSettingsArgsTheme) *NullableRequestSettingsUpdateSettingsArgsTheme {
	return &NullableRequestSettingsUpdateSettingsArgsTheme{value: val, isSet: true}
}

func (v NullableRequestSettingsUpdateSettingsArgsTheme) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestSettingsUpdateSettingsArgsTheme) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


