/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package convex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestTasksListRootTasksArgs type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestTasksListRootTasksArgs{}

// RequestTasksListRootTasksArgs struct for RequestTasksListRootTasksArgs
type RequestTasksListRootTasksArgs struct {
	ProjectId string `json:"projectId"`
}

type _RequestTasksListRootTasksArgs RequestTasksListRootTasksArgs

// NewRequestTasksListRootTasksArgs instantiates a new RequestTasksListRootTasksArgs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestTasksListRootTasksArgs(projectId string) *RequestTasksListRootTasksArgs {
	this := RequestTasksListRootTasksArgs{}
	this.ProjectId = projectId
	return &this
}

// NewRequestTasksListRootTasksArgsWithDefaults instantiates a new RequestTasksListRootTasksArgs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestTasksListRootTasksArgsWithDefaults() *RequestTasksListRootTasksArgs {
	this := RequestTasksListRootTasksArgs{}
	return &this
}

// GetProjectId returns the ProjectId field value
func (o *RequestTasksListRootTasksArgs) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *RequestTasksListRootTasksArgs) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *RequestTasksListRootTasksArgs) SetProjectId(v string) {
	o.ProjectId = v
}

func (o RequestTasksListRootTasksArgs) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestTasksListRootTasksArgs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["projectId"] = o.ProjectId
	return toSerialize, nil
}

func (o *RequestTasksListRootTasksArgs) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"projectId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestTasksListRootTasksArgs := _RequestTasksListRootTasksArgs{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestTasksListRootTasksArgs)

	if err != nil {
		return err
	}

	*o = RequestTasksListRootTasksArgs(varRequestTasksListRootTasksArgs)

	return err
}

type NullableRequestTasksListRootTasksArgs struct {
	value *RequestTasksListRootTasksArgs
	isSet bool
}

func (v NullableRequestTasksListRootTasksArgs) Get() *RequestTasksListRootTasksArgs {
	return v.value
}

func (v *NullableRequestTasksListRootTasksArgs) Set(val *RequestTasksListRootTasksArgs) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestTasksListRootTasksArgs) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestTasksListRootTasksArgs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestTasksListRootTasksArgs(val *RequestTasksListRootTasksArgs) *NullableRequestTasksListRootTasksArgs {
	return &NullableRequestTasksListRootTasksArgs{value: val, isSet: true}
}

func (v NullableRequestTasksListRootTasksArgs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestTasksListRootTasksArgs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


