/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package convex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestProjectsUpdatePositionArgs type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestProjectsUpdatePositionArgs{}

// RequestProjectsUpdatePositionArgs struct for RequestProjectsUpdatePositionArgs
type RequestProjectsUpdatePositionArgs struct {
	Id string `json:"id"`
	PositionX float32 `json:"positionX"`
	PositionY float32 `json:"positionY"`
}

type _RequestProjectsUpdatePositionArgs RequestProjectsUpdatePositionArgs

// NewRequestProjectsUpdatePositionArgs instantiates a new RequestProjectsUpdatePositionArgs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestProjectsUpdatePositionArgs(id string, positionX float32, positionY float32) *RequestProjectsUpdatePositionArgs {
	this := RequestProjectsUpdatePositionArgs{}
	this.Id = id
	this.PositionX = positionX
	this.PositionY = positionY
	return &this
}

// NewRequestProjectsUpdatePositionArgsWithDefaults instantiates a new RequestProjectsUpdatePositionArgs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestProjectsUpdatePositionArgsWithDefaults() *RequestProjectsUpdatePositionArgs {
	this := RequestProjectsUpdatePositionArgs{}
	return &this
}

// GetId returns the Id field value
func (o *RequestProjectsUpdatePositionArgs) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RequestProjectsUpdatePositionArgs) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RequestProjectsUpdatePositionArgs) SetId(v string) {
	o.Id = v
}

// GetPositionX returns the PositionX field value
func (o *RequestProjectsUpdatePositionArgs) GetPositionX() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PositionX
}

// GetPositionXOk returns a tuple with the PositionX field value
// and a boolean to check if the value has been set.
func (o *RequestProjectsUpdatePositionArgs) GetPositionXOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PositionX, true
}

// SetPositionX sets field value
func (o *RequestProjectsUpdatePositionArgs) SetPositionX(v float32) {
	o.PositionX = v
}

// GetPositionY returns the PositionY field value
func (o *RequestProjectsUpdatePositionArgs) GetPositionY() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PositionY
}

// GetPositionYOk returns a tuple with the PositionY field value
// and a boolean to check if the value has been set.
func (o *RequestProjectsUpdatePositionArgs) GetPositionYOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PositionY, true
}

// SetPositionY sets field value
func (o *RequestProjectsUpdatePositionArgs) SetPositionY(v float32) {
	o.PositionY = v
}

func (o RequestProjectsUpdatePositionArgs) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestProjectsUpdatePositionArgs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["positionX"] = o.PositionX
	toSerialize["positionY"] = o.PositionY
	return toSerialize, nil
}

func (o *RequestProjectsUpdatePositionArgs) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"positionX",
		"positionY",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestProjectsUpdatePositionArgs := _RequestProjectsUpdatePositionArgs{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestProjectsUpdatePositionArgs)

	if err != nil {
		return err
	}

	*o = RequestProjectsUpdatePositionArgs(varRequestProjectsUpdatePositionArgs)

	return err
}

type NullableRequestProjectsUpdatePositionArgs struct {
	value *RequestProjectsUpdatePositionArgs
	isSet bool
}

func (v NullableRequestProjectsUpdatePositionArgs) Get() *RequestProjectsUpdatePositionArgs {
	return v.value
}

func (v *NullableRequestProjectsUpdatePositionArgs) Set(val *RequestProjectsUpdatePositionArgs) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestProjectsUpdatePositionArgs) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestProjectsUpdatePositionArgs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestProjectsUpdatePositionArgs(val *RequestProjectsUpdatePositionArgs) *NullableRequestProjectsUpdatePositionArgs {
	return &NullableRequestProjectsUpdatePositionArgs{value: val, isSet: true}
}

func (v NullableRequestProjectsUpdatePositionArgs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestProjectsUpdatePositionArgs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


