/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package convex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestSeedSeedDatabase type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestSeedSeedDatabase{}

// RequestSeedSeedDatabase struct for RequestSeedSeedDatabase
type RequestSeedSeedDatabase struct {
	Args map[string]interface{} `json:"args"`
}

type _RequestSeedSeedDatabase RequestSeedSeedDatabase

// NewRequestSeedSeedDatabase instantiates a new RequestSeedSeedDatabase object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestSeedSeedDatabase(args map[string]interface{}) *RequestSeedSeedDatabase {
	this := RequestSeedSeedDatabase{}
	this.Args = args
	return &this
}

// NewRequestSeedSeedDatabaseWithDefaults instantiates a new RequestSeedSeedDatabase object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestSeedSeedDatabaseWithDefaults() *RequestSeedSeedDatabase {
	this := RequestSeedSeedDatabase{}
	return &this
}

// GetArgs returns the Args field value
func (o *RequestSeedSeedDatabase) GetArgs() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Args
}

// GetArgsOk returns a tuple with the Args field value
// and a boolean to check if the value has been set.
func (o *RequestSeedSeedDatabase) GetArgsOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Args, true
}

// SetArgs sets field value
func (o *RequestSeedSeedDatabase) SetArgs(v map[string]interface{}) {
	o.Args = v
}

func (o RequestSeedSeedDatabase) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestSeedSeedDatabase) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["args"] = o.Args
	return toSerialize, nil
}

func (o *RequestSeedSeedDatabase) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"args",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestSeedSeedDatabase := _RequestSeedSeedDatabase{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestSeedSeedDatabase)

	if err != nil {
		return err
	}

	*o = RequestSeedSeedDatabase(varRequestSeedSeedDatabase)

	return err
}

type NullableRequestSeedSeedDatabase struct {
	value *RequestSeedSeedDatabase
	isSet bool
}

func (v NullableRequestSeedSeedDatabase) Get() *RequestSeedSeedDatabase {
	return v.value
}

func (v *NullableRequestSeedSeedDatabase) Set(val *RequestSeedSeedDatabase) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestSeedSeedDatabase) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestSeedSeedDatabase) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestSeedSeedDatabase(val *RequestSeedSeedDatabase) *NullableRequestSeedSeedDatabase {
	return &NullableRequestSeedSeedDatabase{value: val, isSet: true}
}

func (v NullableRequestSeedSeedDatabase) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestSeedSeedDatabase) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


