/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package convex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestAgentsUpdateStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestAgentsUpdateStatus{}

// RequestAgentsUpdateStatus struct for RequestAgentsUpdateStatus
type RequestAgentsUpdateStatus struct {
	Args RequestAgentsUpdateStatusArgs `json:"args"`
}

type _RequestAgentsUpdateStatus RequestAgentsUpdateStatus

// NewRequestAgentsUpdateStatus instantiates a new RequestAgentsUpdateStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestAgentsUpdateStatus(args RequestAgentsUpdateStatusArgs) *RequestAgentsUpdateStatus {
	this := RequestAgentsUpdateStatus{}
	this.Args = args
	return &this
}

// NewRequestAgentsUpdateStatusWithDefaults instantiates a new RequestAgentsUpdateStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestAgentsUpdateStatusWithDefaults() *RequestAgentsUpdateStatus {
	this := RequestAgentsUpdateStatus{}
	return &this
}

// GetArgs returns the Args field value
func (o *RequestAgentsUpdateStatus) GetArgs() RequestAgentsUpdateStatusArgs {
	if o == nil {
		var ret RequestAgentsUpdateStatusArgs
		return ret
	}

	return o.Args
}

// GetArgsOk returns a tuple with the Args field value
// and a boolean to check if the value has been set.
func (o *RequestAgentsUpdateStatus) GetArgsOk() (*RequestAgentsUpdateStatusArgs, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Args, true
}

// SetArgs sets field value
func (o *RequestAgentsUpdateStatus) SetArgs(v RequestAgentsUpdateStatusArgs) {
	o.Args = v
}

func (o RequestAgentsUpdateStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestAgentsUpdateStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["args"] = o.Args
	return toSerialize, nil
}

func (o *RequestAgentsUpdateStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"args",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestAgentsUpdateStatus := _RequestAgentsUpdateStatus{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestAgentsUpdateStatus)

	if err != nil {
		return err
	}

	*o = RequestAgentsUpdateStatus(varRequestAgentsUpdateStatus)

	return err
}

type NullableRequestAgentsUpdateStatus struct {
	value *RequestAgentsUpdateStatus
	isSet bool
}

func (v NullableRequestAgentsUpdateStatus) Get() *RequestAgentsUpdateStatus {
	return v.value
}

func (v *NullableRequestAgentsUpdateStatus) Set(val *RequestAgentsUpdateStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestAgentsUpdateStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestAgentsUpdateStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestAgentsUpdateStatus(val *RequestAgentsUpdateStatus) *NullableRequestAgentsUpdateStatus {
	return &NullableRequestAgentsUpdateStatus{value: val, isSet: true}
}

func (v NullableRequestAgentsUpdateStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestAgentsUpdateStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


