/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package convex

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestSettingsUpdateSettingsArgs type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestSettingsUpdateSettingsArgs{}

// RequestSettingsUpdateSettingsArgs struct for RequestSettingsUpdateSettingsArgs
type RequestSettingsUpdateSettingsArgs struct {
	AutoLayout *bool `json:"autoLayout,omitempty"`
	AutoSave *bool `json:"autoSave,omitempty"`
	CurrentWorkspace *string `json:"currentWorkspace,omitempty"`
	Language *string `json:"language,omitempty"`
	LeftSidebarCollapsed *bool `json:"leftSidebarCollapsed,omitempty"`
	Notifications *bool `json:"notifications,omitempty"`
	RightSidebarCollapsed *bool `json:"rightSidebarCollapsed,omitempty"`
	SelectedNodeIds []string `json:"selectedNodeIds,omitempty"`
	SelectedProjectId *string `json:"selectedProjectId,omitempty"`
	ShowBackground *bool `json:"showBackground,omitempty"`
	ShowMiniMap *bool `json:"showMiniMap,omitempty"`
	Theme *RequestSettingsUpdateSettingsArgsTheme `json:"theme,omitempty"`
	UserId string `json:"userId"`
}

type _RequestSettingsUpdateSettingsArgs RequestSettingsUpdateSettingsArgs

// NewRequestSettingsUpdateSettingsArgs instantiates a new RequestSettingsUpdateSettingsArgs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestSettingsUpdateSettingsArgs(userId string) *RequestSettingsUpdateSettingsArgs {
	this := RequestSettingsUpdateSettingsArgs{}
	this.UserId = userId
	return &this
}

// NewRequestSettingsUpdateSettingsArgsWithDefaults instantiates a new RequestSettingsUpdateSettingsArgs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestSettingsUpdateSettingsArgsWithDefaults() *RequestSettingsUpdateSettingsArgs {
	this := RequestSettingsUpdateSettingsArgs{}
	return &this
}

// GetAutoLayout returns the AutoLayout field value if set, zero value otherwise.
func (o *RequestSettingsUpdateSettingsArgs) GetAutoLayout() bool {
	if o == nil || IsNil(o.AutoLayout) {
		var ret bool
		return ret
	}
	return *o.AutoLayout
}

// GetAutoLayoutOk returns a tuple with the AutoLayout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestSettingsUpdateSettingsArgs) GetAutoLayoutOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoLayout) {
		return nil, false
	}
	return o.AutoLayout, true
}

// HasAutoLayout returns a boolean if a field has been set.
func (o *RequestSettingsUpdateSettingsArgs) HasAutoLayout() bool {
	if o != nil && !IsNil(o.AutoLayout) {
		return true
	}

	return false
}

// SetAutoLayout gets a reference to the given bool and assigns it to the AutoLayout field.
func (o *RequestSettingsUpdateSettingsArgs) SetAutoLayout(v bool) {
	o.AutoLayout = &v
}

// GetAutoSave returns the AutoSave field value if set, zero value otherwise.
func (o *RequestSettingsUpdateSettingsArgs) GetAutoSave() bool {
	if o == nil || IsNil(o.AutoSave) {
		var ret bool
		return ret
	}
	return *o.AutoSave
}

// GetAutoSaveOk returns a tuple with the AutoSave field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestSettingsUpdateSettingsArgs) GetAutoSaveOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoSave) {
		return nil, false
	}
	return o.AutoSave, true
}

// HasAutoSave returns a boolean if a field has been set.
func (o *RequestSettingsUpdateSettingsArgs) HasAutoSave() bool {
	if o != nil && !IsNil(o.AutoSave) {
		return true
	}

	return false
}

// SetAutoSave gets a reference to the given bool and assigns it to the AutoSave field.
func (o *RequestSettingsUpdateSettingsArgs) SetAutoSave(v bool) {
	o.AutoSave = &v
}

// GetCurrentWorkspace returns the CurrentWorkspace field value if set, zero value otherwise.
func (o *RequestSettingsUpdateSettingsArgs) GetCurrentWorkspace() string {
	if o == nil || IsNil(o.CurrentWorkspace) {
		var ret string
		return ret
	}
	return *o.CurrentWorkspace
}

// GetCurrentWorkspaceOk returns a tuple with the CurrentWorkspace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestSettingsUpdateSettingsArgs) GetCurrentWorkspaceOk() (*string, bool) {
	if o == nil || IsNil(o.CurrentWorkspace) {
		return nil, false
	}
	return o.CurrentWorkspace, true
}

// HasCurrentWorkspace returns a boolean if a field has been set.
func (o *RequestSettingsUpdateSettingsArgs) HasCurrentWorkspace() bool {
	if o != nil && !IsNil(o.CurrentWorkspace) {
		return true
	}

	return false
}

// SetCurrentWorkspace gets a reference to the given string and assigns it to the CurrentWorkspace field.
func (o *RequestSettingsUpdateSettingsArgs) SetCurrentWorkspace(v string) {
	o.CurrentWorkspace = &v
}

// GetLanguage returns the Language field value if set, zero value otherwise.
func (o *RequestSettingsUpdateSettingsArgs) GetLanguage() string {
	if o == nil || IsNil(o.Language) {
		var ret string
		return ret
	}
	return *o.Language
}

// GetLanguageOk returns a tuple with the Language field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestSettingsUpdateSettingsArgs) GetLanguageOk() (*string, bool) {
	if o == nil || IsNil(o.Language) {
		return nil, false
	}
	return o.Language, true
}

// HasLanguage returns a boolean if a field has been set.
func (o *RequestSettingsUpdateSettingsArgs) HasLanguage() bool {
	if o != nil && !IsNil(o.Language) {
		return true
	}

	return false
}

// SetLanguage gets a reference to the given string and assigns it to the Language field.
func (o *RequestSettingsUpdateSettingsArgs) SetLanguage(v string) {
	o.Language = &v
}

// GetLeftSidebarCollapsed returns the LeftSidebarCollapsed field value if set, zero value otherwise.
func (o *RequestSettingsUpdateSettingsArgs) GetLeftSidebarCollapsed() bool {
	if o == nil || IsNil(o.LeftSidebarCollapsed) {
		var ret bool
		return ret
	}
	return *o.LeftSidebarCollapsed
}

// GetLeftSidebarCollapsedOk returns a tuple with the LeftSidebarCollapsed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestSettingsUpdateSettingsArgs) GetLeftSidebarCollapsedOk() (*bool, bool) {
	if o == nil || IsNil(o.LeftSidebarCollapsed) {
		return nil, false
	}
	return o.LeftSidebarCollapsed, true
}

// HasLeftSidebarCollapsed returns a boolean if a field has been set.
func (o *RequestSettingsUpdateSettingsArgs) HasLeftSidebarCollapsed() bool {
	if o != nil && !IsNil(o.LeftSidebarCollapsed) {
		return true
	}

	return false
}

// SetLeftSidebarCollapsed gets a reference to the given bool and assigns it to the LeftSidebarCollapsed field.
func (o *RequestSettingsUpdateSettingsArgs) SetLeftSidebarCollapsed(v bool) {
	o.LeftSidebarCollapsed = &v
}

// GetNotifications returns the Notifications field value if set, zero value otherwise.
func (o *RequestSettingsUpdateSettingsArgs) GetNotifications() bool {
	if o == nil || IsNil(o.Notifications) {
		var ret bool
		return ret
	}
	return *o.Notifications
}

// GetNotificationsOk returns a tuple with the Notifications field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestSettingsUpdateSettingsArgs) GetNotificationsOk() (*bool, bool) {
	if o == nil || IsNil(o.Notifications) {
		return nil, false
	}
	return o.Notifications, true
}

// HasNotifications returns a boolean if a field has been set.
func (o *RequestSettingsUpdateSettingsArgs) HasNotifications() bool {
	if o != nil && !IsNil(o.Notifications) {
		return true
	}

	return false
}

// SetNotifications gets a reference to the given bool and assigns it to the Notifications field.
func (o *RequestSettingsUpdateSettingsArgs) SetNotifications(v bool) {
	o.Notifications = &v
}

// GetRightSidebarCollapsed returns the RightSidebarCollapsed field value if set, zero value otherwise.
func (o *RequestSettingsUpdateSettingsArgs) GetRightSidebarCollapsed() bool {
	if o == nil || IsNil(o.RightSidebarCollapsed) {
		var ret bool
		return ret
	}
	return *o.RightSidebarCollapsed
}

// GetRightSidebarCollapsedOk returns a tuple with the RightSidebarCollapsed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestSettingsUpdateSettingsArgs) GetRightSidebarCollapsedOk() (*bool, bool) {
	if o == nil || IsNil(o.RightSidebarCollapsed) {
		return nil, false
	}
	return o.RightSidebarCollapsed, true
}

// HasRightSidebarCollapsed returns a boolean if a field has been set.
func (o *RequestSettingsUpdateSettingsArgs) HasRightSidebarCollapsed() bool {
	if o != nil && !IsNil(o.RightSidebarCollapsed) {
		return true
	}

	return false
}

// SetRightSidebarCollapsed gets a reference to the given bool and assigns it to the RightSidebarCollapsed field.
func (o *RequestSettingsUpdateSettingsArgs) SetRightSidebarCollapsed(v bool) {
	o.RightSidebarCollapsed = &v
}

// GetSelectedNodeIds returns the SelectedNodeIds field value if set, zero value otherwise.
func (o *RequestSettingsUpdateSettingsArgs) GetSelectedNodeIds() []string {
	if o == nil || IsNil(o.SelectedNodeIds) {
		var ret []string
		return ret
	}
	return o.SelectedNodeIds
}

// GetSelectedNodeIdsOk returns a tuple with the SelectedNodeIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestSettingsUpdateSettingsArgs) GetSelectedNodeIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.SelectedNodeIds) {
		return nil, false
	}
	return o.SelectedNodeIds, true
}

// HasSelectedNodeIds returns a boolean if a field has been set.
func (o *RequestSettingsUpdateSettingsArgs) HasSelectedNodeIds() bool {
	if o != nil && !IsNil(o.SelectedNodeIds) {
		return true
	}

	return false
}

// SetSelectedNodeIds gets a reference to the given []string and assigns it to the SelectedNodeIds field.
func (o *RequestSettingsUpdateSettingsArgs) SetSelectedNodeIds(v []string) {
	o.SelectedNodeIds = v
}

// GetSelectedProjectId returns the SelectedProjectId field value if set, zero value otherwise.
func (o *RequestSettingsUpdateSettingsArgs) GetSelectedProjectId() string {
	if o == nil || IsNil(o.SelectedProjectId) {
		var ret string
		return ret
	}
	return *o.SelectedProjectId
}

// GetSelectedProjectIdOk returns a tuple with the SelectedProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestSettingsUpdateSettingsArgs) GetSelectedProjectIdOk() (*string, bool) {
	if o == nil || IsNil(o.SelectedProjectId) {
		return nil, false
	}
	return o.SelectedProjectId, true
}

// HasSelectedProjectId returns a boolean if a field has been set.
func (o *RequestSettingsUpdateSettingsArgs) HasSelectedProjectId() bool {
	if o != nil && !IsNil(o.SelectedProjectId) {
		return true
	}

	return false
}

// SetSelectedProjectId gets a reference to the given string and assigns it to the SelectedProjectId field.
func (o *RequestSettingsUpdateSettingsArgs) SetSelectedProjectId(v string) {
	o.SelectedProjectId = &v
}

// GetShowBackground returns the ShowBackground field value if set, zero value otherwise.
func (o *RequestSettingsUpdateSettingsArgs) GetShowBackground() bool {
	if o == nil || IsNil(o.ShowBackground) {
		var ret bool
		return ret
	}
	return *o.ShowBackground
}

// GetShowBackgroundOk returns a tuple with the ShowBackground field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestSettingsUpdateSettingsArgs) GetShowBackgroundOk() (*bool, bool) {
	if o == nil || IsNil(o.ShowBackground) {
		return nil, false
	}
	return o.ShowBackground, true
}

// HasShowBackground returns a boolean if a field has been set.
func (o *RequestSettingsUpdateSettingsArgs) HasShowBackground() bool {
	if o != nil && !IsNil(o.ShowBackground) {
		return true
	}

	return false
}

// SetShowBackground gets a reference to the given bool and assigns it to the ShowBackground field.
func (o *RequestSettingsUpdateSettingsArgs) SetShowBackground(v bool) {
	o.ShowBackground = &v
}

// GetShowMiniMap returns the ShowMiniMap field value if set, zero value otherwise.
func (o *RequestSettingsUpdateSettingsArgs) GetShowMiniMap() bool {
	if o == nil || IsNil(o.ShowMiniMap) {
		var ret bool
		return ret
	}
	return *o.ShowMiniMap
}

// GetShowMiniMapOk returns a tuple with the ShowMiniMap field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestSettingsUpdateSettingsArgs) GetShowMiniMapOk() (*bool, bool) {
	if o == nil || IsNil(o.ShowMiniMap) {
		return nil, false
	}
	return o.ShowMiniMap, true
}

// HasShowMiniMap returns a boolean if a field has been set.
func (o *RequestSettingsUpdateSettingsArgs) HasShowMiniMap() bool {
	if o != nil && !IsNil(o.ShowMiniMap) {
		return true
	}

	return false
}

// SetShowMiniMap gets a reference to the given bool and assigns it to the ShowMiniMap field.
func (o *RequestSettingsUpdateSettingsArgs) SetShowMiniMap(v bool) {
	o.ShowMiniMap = &v
}

// GetTheme returns the Theme field value if set, zero value otherwise.
func (o *RequestSettingsUpdateSettingsArgs) GetTheme() RequestSettingsUpdateSettingsArgsTheme {
	if o == nil || IsNil(o.Theme) {
		var ret RequestSettingsUpdateSettingsArgsTheme
		return ret
	}
	return *o.Theme
}

// GetThemeOk returns a tuple with the Theme field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestSettingsUpdateSettingsArgs) GetThemeOk() (*RequestSettingsUpdateSettingsArgsTheme, bool) {
	if o == nil || IsNil(o.Theme) {
		return nil, false
	}
	return o.Theme, true
}

// HasTheme returns a boolean if a field has been set.
func (o *RequestSettingsUpdateSettingsArgs) HasTheme() bool {
	if o != nil && !IsNil(o.Theme) {
		return true
	}

	return false
}

// SetTheme gets a reference to the given RequestSettingsUpdateSettingsArgsTheme and assigns it to the Theme field.
func (o *RequestSettingsUpdateSettingsArgs) SetTheme(v RequestSettingsUpdateSettingsArgsTheme) {
	o.Theme = &v
}

// GetUserId returns the UserId field value
func (o *RequestSettingsUpdateSettingsArgs) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *RequestSettingsUpdateSettingsArgs) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *RequestSettingsUpdateSettingsArgs) SetUserId(v string) {
	o.UserId = v
}

func (o RequestSettingsUpdateSettingsArgs) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestSettingsUpdateSettingsArgs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AutoLayout) {
		toSerialize["autoLayout"] = o.AutoLayout
	}
	if !IsNil(o.AutoSave) {
		toSerialize["autoSave"] = o.AutoSave
	}
	if !IsNil(o.CurrentWorkspace) {
		toSerialize["currentWorkspace"] = o.CurrentWorkspace
	}
	if !IsNil(o.Language) {
		toSerialize["language"] = o.Language
	}
	if !IsNil(o.LeftSidebarCollapsed) {
		toSerialize["leftSidebarCollapsed"] = o.LeftSidebarCollapsed
	}
	if !IsNil(o.Notifications) {
		toSerialize["notifications"] = o.Notifications
	}
	if !IsNil(o.RightSidebarCollapsed) {
		toSerialize["rightSidebarCollapsed"] = o.RightSidebarCollapsed
	}
	if !IsNil(o.SelectedNodeIds) {
		toSerialize["selectedNodeIds"] = o.SelectedNodeIds
	}
	if !IsNil(o.SelectedProjectId) {
		toSerialize["selectedProjectId"] = o.SelectedProjectId
	}
	if !IsNil(o.ShowBackground) {
		toSerialize["showBackground"] = o.ShowBackground
	}
	if !IsNil(o.ShowMiniMap) {
		toSerialize["showMiniMap"] = o.ShowMiniMap
	}
	if !IsNil(o.Theme) {
		toSerialize["theme"] = o.Theme
	}
	toSerialize["userId"] = o.UserId
	return toSerialize, nil
}

func (o *RequestSettingsUpdateSettingsArgs) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"userId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestSettingsUpdateSettingsArgs := _RequestSettingsUpdateSettingsArgs{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestSettingsUpdateSettingsArgs)

	if err != nil {
		return err
	}

	*o = RequestSettingsUpdateSettingsArgs(varRequestSettingsUpdateSettingsArgs)

	return err
}

type NullableRequestSettingsUpdateSettingsArgs struct {
	value *RequestSettingsUpdateSettingsArgs
	isSet bool
}

func (v NullableRequestSettingsUpdateSettingsArgs) Get() *RequestSettingsUpdateSettingsArgs {
	return v.value
}

func (v *NullableRequestSettingsUpdateSettingsArgs) Set(val *RequestSettingsUpdateSettingsArgs) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestSettingsUpdateSettingsArgs) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestSettingsUpdateSettingsArgs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestSettingsUpdateSettingsArgs(val *RequestSettingsUpdateSettingsArgs) *NullableRequestSettingsUpdateSettingsArgs {
	return &NullableRequestSettingsUpdateSettingsArgs{value: val, isSet: true}
}

func (v NullableRequestSettingsUpdateSettingsArgs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestSettingsUpdateSettingsArgs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


