// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/denkhaus/agents/pkg/tools/tavily

package tavily

#ToolSetName:            "tavily_toolset"
#DefaultSearchToolName:  "tavily_search"
#DefaultCrawlToolName:   "tavily_crawl"
#DefaultExtractToolName: "tavily_extract"
#DefaultMapToolName:     "tavily_map"

// TavilyToolSet implements the ToolSet interface for Tavily API.
#TavilyToolSet: {
	ApiKey:         string
	SearchEnabled:  bool
	CrawlEnabled:   bool
	ExtractEnabled: bool
	MapEnabled:     bool
}

// Search tool
_#searchArgs: {
	query:           string @go(Query)
	search_depth?:   string @go(SearchDepth)
	include_answer?: bool   @go(IncludeAnswer)
	include_domains?: [...string] @go(IncludeDomains,[]string)
	exclude_domains?: [...string] @go(ExcludeDomains,[]string)
}

// Crawl tool
_#crawlArgs: {
	url:        string @go(URL)
	max_depth?: int    @go(MaxDepth)
}

// Extract tool
_#extractArgs: {
	urls: [...string] @go(URLs,[]string)
}

// Map tool
_#mapArgs: {
	url:        string @go(URL)
	max_depth?: int    @go(MaxDepth)
}
